### ISSUE TITLE
Non working wallpapers

### ISSUE THREAD

**Issue by alvarotorijano** [RogueMaster/flipperzero-firmware-wPlugins#1006]
### Describe the bug.

After this update background wallpapers are no longer working

### Reproduction

Update
Upload or leave the stock manifest
Keep pressing the center button to loop through all animations
Nothing will happen

**Comment by RogueMaster** [comment]
Check your CFW Settings => Interface => Desktop => Animations configuration and that you didn't install the NoAnim Version
