### ISSUE TITLE
Unable to remove hopper frequency

### ISSUE THREAD

**Issue by alchemixxxx** [RogueMaster/flipperzero-firmware-wPlugins#1010]
0.96.1 12-12-2023 RC1

1. CFW>Protocols>SubGHz Frequencies>Hopper Frequencies>Hopper Freq 310.00
2. Remove hopper freq
3. NULL pointer dereference

**Comment by RogueMaster** [comment]
Will review further, I see on regular releases this can be replicated, it only happens for the first item too

**Comment by RogueMaster** [comment]
This should be fixed for next release
