### ISSUE TITLE
nfc emulation doesn't seem to work whenever i install

### ISSUE THREAD

**Issue by gizmogamesyt** [RogueMaster/flipperzero-firmware-wPlugins#1012]
### Describe the bug.

i'm doing everything properly, or so i think, but i can't get the nfc emulation at all to work

### Reproduction

it happens during install

### Anything else?

i am fairly new to all of this so pardon my dust

btw i replied

**Comment by RogueMaster** [comment]
Please explain exactly what build you are using and everything you did to make you think you were doing it "properly"

**Comment by gizmogamesyt** [comment]
i used the web installer

**Comment by gizmogamesyt** [comment]
> Please explain exactly what build you are using and everything you did to make you think you were doing it "properly"

i used the web installer and it says it can't parse the uid for amiibos and other nfc that i've saved

**Comment by gizmogamesyt** [comment]
https://github.com/RogueMaster/flipperzero-firmware-wPlugins/issues/1012#issuecomment-1864145841_
