### ISSUE TITLE
When using SLIX-L on ISO15693 NFC Tags it can not be saved / emulated

### ISSUE THREAD

**Issue by bird-vogel** [RogueMaster/flipperzero-firmware-wPlugins#1013]
### Describe the bug.

When unlocking an ISO15693 Tag (as contributed by g3gg0) via the SLIX-L action, F0 displays an error message, that it could not be saved. However there is an entry saved for the tag (file name starts with "SLIX_"). 

Trying to emulate said entry results in an "Can not parse file" error.

It is however to "unlock" the tag and emulate it right after, however it can not be saved (or the save will result in the same as above - "Can not parse file").

### Reproduction

Reading ISO15693 Tag:
1. NFC --> Extra Actions
2. Unlock SLIX-L --> Auth as TonieBox
3. Read Tag
4. Error Message about failed Save will appear

Emulating:
1. NFC -->Saved
2. Select Entry
3. Error Message is displayd "Can not parse file"

**Comment by RogueMaster** [comment]
Please test with the RC releases for NFC refactors
