### ISSUE TITLE
Need to wait 5sec to shutdown the flipper with back button on v97.2

### ISSUE THREAD

**Issue by casimirextreme** [RogueMaster/flipperzero-firmware-wPlugins#1020]
This is more a request than an issue. On v93.2, shutting down the flipper when keeping the back button is instantaneous. On v97.2, it takes 5 sec due to this timeout:

https://github.com/RogueMaster/flipperzero-firmware-wPlugins/blob/5566e5434e87596a2a63b86d4a9fd6c14c4c2a5d/applications/services/desktop/views/desktop_view_main.c#L22

Would it be possible to stick to the same behavior as on v93.2 ?
Putting this timeout value to 500 should restore it. Thanks.

**Comment by RogueMaster** [comment]
Fixed on refactors, thank you!
