### ISSUE TITLE
errors exiting apps (usually games, or other apps)

### ISSUE THREAD

**Issue by anickname028** [RogueMaster/flipperzero-firmware-wPlugins#1025]
### Describe the bug.

flipper crashes due to errors, usually out of memory but sometimes others.

### Reproduction

1. open apps menu
2. open a heavy-memory app
3. hope that it crashes on close and reopening (it doesn't work all the time)

### Target

Flipper Zero

### Logs

```Text
not recorded
```

**Comment by RogueMaster** [comment]
Depending on app memory usage, sometimes a restart can be needed... back and left will restart the device pretty quickly... the heavy memory apps need to be tracked and cleared for a smaller memory foot print to decrease the crashes... most apps have the stack size pre-assigned by original developers... at this time, you are welcomed to try different apps you opened to produce your crash and test them with smaller stack size to see if they function correctly... send changes one PR per app...
