### ISSUE TITLE
missind dependency with macos

### ISSUE THREAD

**Issue by magnum** [RogueMaster/flipperzero-firmware-wPlugins#103]
when i run 
`docker-compose exec dev ./fbt`
i receive this error
`qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory`
any ideas?

**Comment by RogueMaster** [comment]
try following the [macOS guide](https://github.com/RogueMaster/flipperzero-firmware-wPlugins/blob/unleashed/MACOS_GUIDE.md)

**Comment by RogueMaster** [comment]
also, inquire on the main discord before opening up an issue here or on the main github
