### ISSUE TITLE
Errors when transmitting from Sub-GHz

### ISSUE THREAD

**Issue by manspace80** [RogueMaster/flipperzero-firmware-wPlugins#1032]
### Describe the bug.

If I go to saved Sub-GHz and want to emulate it, the transmission simply switches to scanning.

### Reproduction

1. Sub-GHz
2. Saved
3. Misc
4. Go1
5. Emulate
6. Send <- It switches to Scan

**Comment by RogueMaster** [comment]
This is not an issue that can be replicated on present release or release candidate builds.
