### ISSUE TITLE
ESP32 Marauder throws "Cannot create app folder" after update to RM0208-2318-0.97.2-f563329

### ISSUE THREAD

**Issue by jonnyborbs** [RogueMaster/flipperzero-firmware-wPlugins#1033]
### Describe the bug.

This just started after updating to RM0208-2318-0.97.2-f563329. 

I did delete the /apps folder before upgrading as I always do, particularly since this was a bump from 0.93 to 0.97

Now, when opening the ESP32 WiFi Marauder app it throws the following error
![Screenshot-20240209-164804](https://github.com/RogueMaster/flipperzero-firmware-wPlugins/assets/25127543/ebf50adf-f8f3-4b04-be0e-1b64edb55a90)

![Screenshot-20240209-164812](https://github.com/RogueMaster/flipperzero-firmware-wPlugins/assets/25127543/086ea133-0a96-4462-94bb-5180416c9450)

If you click past it, things seem to work OK still. The app is set to save all logs and PCAPs to the WiFi board's internal SD card. I can confirm I can list the contents of that SD card from within the app, and even did an update to Marauder 0.13.7 using the in-app flash utility - so it's not a hardware issue.

Not sure what this is about.

### Reproduction

- Update to RM0208-2318-0.97.2-f563329
- Open ESP32 WiFi Marauder
- Error is displayed

Can't confirm this is the case outside of my setup.

**Comment by RogueMaster** [comment]
A marauder update will come soon, but I don't think it will fix this issue... we shall see...

**Comment by jonnyborbs** [comment]
For what it's worth, I also checked out the ESP Flasher utility and noticed in this build, it has no app_data folder and thus no firmware binaries to swap between. IIRC that app and this one come from the same source, right?

**Comment by RogueMaster** [comment]
Fixed by Latest Release RM0210-1603-0.97.2-2707a31
