### ISSUE TITLE
Main screen no animation

### ISSUE THREAD

**Issue by neoteknic** [RogueMaster/flipperzero-firmware-wPlugins#1038]
### Describe the bug.

Since few weeks, I have a bug = no animation on main screen, blank, only bluetooth sd, battery logo.
I tried to empty the dolmphin folder, but same problem after re update. 
Happen since (or maybe the previous):
[RM0208-2318-0.97.2-f563329](https://github.com/RogueMaster/flipperzero-firmware-wPlugins/releases/tag/RM0208-2318-0.97.2-f563329)

Still present in:
[RM0221-1919-0.98.4-1379c9c](https://github.com/RogueMaster/flipperzero-firmware-wPlugins/releases/tag/RM0221-1919-0.98.4-1379c9c)

Evrything else is OK.

### Reproduction

Install RM0221-1919-0.98.4-1379c9c from a work  RM version
No amitation on screen.

**Comment by RogueMaster** [comment]
Default option resulting in No Animations is being looked into. In the meantime, please go into CFW Settings => Interface => Desktop and change the Animations option to your desired set.

You can also place [this](https://github.com/RogueMaster/awesome-flipperzero-withModules/tree/rogue_main/graphics/dolphin-ManifestSwitcher) folder contents in your dolphin folder to have many more options in your Animations selector.
