### ISSUE TITLE
Web Installer type error

### ISSUE THREAD

**Issue by edmadrak** [RogueMaster/flipperzero-firmware-wPlugins#1039]
### Describe the bug.

Clicked on the web installer button, when attempting to load the firmware it produced the following error:

TypeError: Cannot read properties of undefined (reading 'data')

Failed to fetch firmware: TypeError: Cannot read properties of undefined (reading 'data')
TypeError: Cannot read properties of undefined (reading 'data')

File Name used - "RM0222-1041-0.98.4-31a21ce"
URL Clicked - https://lab.flipper.net/?url=https%3A%2F%2Frogue-master.net%2F%3Ffile%3DRM0222-1041-0.98.4-31a21ce.tgz&channel=RM0222-1041-0.98.4-31a21ce&version=0.98.4

### Reproduction

1. Connect Flipper Zero and pair
2. Click above link
3. Click Install on RM firmware

**Comment by gandlers** [comment]
Thought I was doing something wrong as I also had this issue.

**Comment by RogueMaster** [comment]
Please use install with TGZ until it is resolved

**Comment by RogueMaster** [comment]
Should be working now, sorry for the inconvenience 😄 Enjoy Flipper!

**Comment by edmadrak** [comment]
Confirmed works as expected. Many thanks for your continued efforts!
