### ISSUE TITLE
Load FAP files through the plugin and games menu if possible

### ISSUE THREAD

**Issue by YoshiFan501** [RogueMaster/flipperzero-firmware-wPlugins#104]
**Is your feature request related to a problem? Please describe.**
After updating to the ELF loader, the games and plugins on external are only openable after opening the ELF Loader, unlike all of them being organized under games or plugins. 

**Describe the solution you'd like**
Allow the Plugin and Games menu to show or load .FAP files when put into the application.fam file under apps/meta. (when I compiled the firmware myself with them readded to the file, it has both internal and externals on the flipper)

**Describe alternatives you've considered**
Changing Plugins and games to their own ELF Loader programs and seperate folders in the sdcard for easier organization

**Additional context**
N'A

**Comment by RogueMaster** [comment]
This would be great... wouldn't be attempted till FAPs are worked into main... feel free to develop :)
