### ISSUE TITLE
UHF RFID app freezes

### ISSUE THREAD

**Issue by torreswb** [RogueMaster/flipperzero-firmware-wPlugins#1040]
### Describe the bug.

Since upgrading from 97.2 to 98.4 the uhf app freezes.  If plugged in to a power supply with the m100 attached it may work for seconds then freeze.  If i try to use the app with the M100 module without power attached it freezes instantly.  Both were working before.

### Reproduction

plug in module
open app
with power plugged in read an rfid item.  Sometimes it will read, sometimes it freezes.
when power isnt plugged in you need hit retry to detect module, this always happened.  Then it freezes.

### Anything else?

Thanks for the help, I used this app all the time for work.

**Comment by RogueMaster** [comment]
This repo is for the flipper firmware. The readme has the original repo linked for you to try to request a fix.
