### ISSUE TITLE
Payload starts with 0x on airtag 

### ISSUE THREAD

**Issue by kenneth7398** [RogueMaster/flipperzero-firmware-wPlugins#1048]
### Describe the bug.

my payload starts with 0x on find my flipper so i dont know how to add it manually as there is no x to type

### Reproduction

my payload starts with 0x on find my flipper so i dont know how to add it manually as there is no x to type  pls help

**Comment by RogueMaster** [comment]
@kenneth7398 Please don't open tickets here regarding apps, open them in the respective repository for the app. If you open another issue here, you will be blocked form doing so. But also, don't open an issue with the app either. Read up on the documentation that is provided with the app.
