### ISSUE TITLE
NFC Bug in (RM0329-0331-0.100.2-95748e8)

### ISSUE THREAD

**Issue by freesofia** [RogueMaster/flipperzero-firmware-wPlugins#1052]
### Describe the bug.

After the last update, which does not go through the WEB Installer (only manually through the qFlipper app with file: ![2024-03-29 11_01_26-Window](https://github.com/RogueMaster/flipperzero-firmware-wPlugins/assets/13334726/0bfd9668-f96e-4d3b-9962-221491dc1e5a).tgz), the device freezes and restarts when selecting NFC!

### Reproduction

1. Switch on
2. Press the button select app
3. Select NFC
4. Crash & Reboot

**Comment by gades** [comment]
The same issue for me

**Comment by RogueMaster** [comment]
This will be checked into but is a known issue being worked on
