### ISSUE TITLE
Error: Application "Passport" not found!

### ISSUE THREAD

**Issue by alexbayker** [RogueMaster/flipperzero-firmware-wPlugins#1056]
"Error: Application "Passport" not found!" After right button click on main screen

**Comment by hongster** [comment]
This issue starts occurring after updating firmware to RM0416-0415-0.100.4-22e2176.

![Screenshot-20240417-003914](https://github.com/RogueMaster/flipperzero-firmware-wPlugins/assets/89811/18636ed7-1e62-4250-9f63-320f8d0712b7)

![Screenshot-20240417-004224](https://github.com/RogueMaster/flipperzero-firmware-wPlugins/assets/89811/5b33080e-a107-46ec-a793-8f7dfceb7d96)

**Comment by RogueMaster** [comment]
Fixed for next release
