### ISSUE TITLE
Sub-ghz

### ISSUE THREAD

**Issue by bindix3737** [RogueMaster/flipperzero-firmware-wPlugins#1059]

**Comment by RogueMaster** [comment]
Did you try to bypass or extend ranges?

**Comment by bindix3737** [comment]
Bank card emulate future required
Nfc Payment not emulated 
Any credit card or Debit card

**Comment by bindix3737** [comment]
> Did you try to bypass or extend ranges?

Not work

**Comment by RogueMaster** [comment]
> Bank card emulate future required Nfc Payment not emulated Any credit card or Debit card

None of these are supposed to work....

**Comment by bindix3737** [comment]
> > Bank card emulate future required Nfc Payment not emulated Any credit card or Debit card
> 
> None of these are supposed to work....

Hmm...
Any reason

**Comment by RogueMaster** [comment]
> > > Bank card emulate future required Nfc Payment not emulated Any credit card or Debit card
> > 
> > 
> > None of these are supposed to work....
> 
> Hmm... Any reason

You haven't made the functionality yet, seems like you want it... start learning and you may find its harder to get that feature to work than you think... but maybe you can figure it out and bring it to flipper for everyone...

**Comment by bindix3737** [comment]
> > > > Bank card emulate future required Nfc Payment not emulated Any credit card or Debit card
> > > 
> > > 
> > > None of these are supposed to work....
> > 
> > 
> > Hmm... Any reason
> 
> You haven't made the functionality yet, seems like you want it... start learning and you may find its harder to get that feature to work than you think... but maybe you can figure it out and bring it to flipper for everyone...

I don't know how to solve problems, so I'm telling you

**Comment by bindix3737** [comment]
OK thanks,
But , I don't know how to solve problems, so I'm telling you
