### ISSUE TITLE
Don't remove previous release assets

### ISSUE THREAD

**Issue by JulyIghor** [RogueMaster/flipperzero-firmware-wPlugins#106]
Please don't remove previous release assets.
For example Games folder crashes in latest release, so I wish to roll back, but can't, since it is not available here anymore.

**Comment by RogueMaster** [comment]
Your complaint is noted, but will not be followed. If you want older releases, save them or compile it yourself. I'm not trying to answer any questions or issues about older firmware. Some older builds can be found here: https://flipper.pingywon.com/flipper/firmware-unleashed-dfu/Firmware_Hacked_By_Rogue_Master%20-%20Download%20newest%20file!/

**Comment by JulyIghor** [comment]
> Your complaint is noted, but will not be followed. If you want older releases, save them or compile it yourself. I'm not trying to answer any questions or issues about older firmware. Some older builds can be found here: https://flipper.pingywon.com/flipper/firmware-unleashed-dfu/Firmware_Hacked_By_Rogue_Master%20-%20Download%20newest%20file!/

Thanks! I'll use that url here https://t.me/FlipperNews
