### ISSUE TITLE
Duplicate resource packages in the releases

### ISSUE THREAD

**Issue by cokyrain** [RogueMaster/flipperzero-firmware-wPlugins#1066]
### Describe the bug.

![1](https://github.com/RogueMaster/flipperzero-firmware-wPlugins/assets/75012356/c8f20c52-fe08-41c6-8aa4-2e3129735202)
![2](https://github.com/RogueMaster/flipperzero-firmware-wPlugins/assets/75012356/c9e8ece6-af5f-4b5b-8f3d-bbee045d3581)

### Reproduction

File names resources.tar and resources.tar.gz

**Comment by RogueMaster** [comment]
Thank you, fixed for future releases...
