### ISSUE TITLE
External App is added crachreboot

### ISSUE THREAD

**Issue by DroWez** [RogueMaster/flipperzero-firmware-wPlugins#1067]
### Describe the bug.

Crash Reboots when the External App is added to the Mainmenu

### Reproduction

CFW SET >> Interface >>Main Menu >> Add App>> Extetnal app >>  choose any application

**Comment by RogueMaster** [comment]
Thanks will check into this...

**Comment by RogueMaster** [comment]
This is fixed for the next Patreon release and the next public release.
