### ISSUE TITLE
Sub-GHz app doesn't decode (Pocsag) anymore...

### ISSUE THREAD

**Issue by dl9sec** [RogueMaster/flipperzero-firmware-wPlugins#1068]
### Describe the bug.

With the latest RM firmware the Sub-GHz app doesn't decode anymore (predecessor RM0429-1240-0.101.3-a5550b3 worked fine).
I can see and hear, that a signal is received, but there is no decoding (nor in "Read", neither in "Read RAW").

### Reproduction

1. Renamed "SD Card/subghz/assets/setting_user.txt" to "setting_user.txt.org".
2. Renamed "SD Card/subghz/assets/setting_user.pocsag" to "setting_user.txt".
3. Rebooted Flipper
4. Started "Sub-Ghz" -> "Read"
5. Configured frequency to "439.98" at the end of the frequency list

**Comment by RogueMaster** [comment]
Use POCSAG app for pocsag

**Comment by dl9sec** [comment]
Sure, but not for recording pocsag transmissions

**Comment by RogueMaster** [comment]
Understood will get re-added for next build. Could you help me understand, what can you do with a recorded POCSAG transmission?

**Comment by dl9sec** [comment]
E.g. to help xMasterX to debug the Pocsag pager app (see https://github.com/xMasterX/flipper-pager/issues/14).
The Sub-Ghz app is very helpful here and it is a pitty when the app can not decode Pocsag correctly...

**Comment by RogueMaster** [comment]
Damn, you don't have a real use case? It's a pitty you don't have a real use for this 🤦🏼
