### ISSUE TITLE
[NFC] - Read multiple NFC does not improve flipper level

### ISSUE THREAD

**Issue by Radion94200** [RogueMaster/flipperzero-firmware-wPlugins#1077]
### Describe the bug.

- When I read multiple NFC tags during a workshop for example, the score of the flipper zero is not increase after some readings

### Reproduction

1. read multiple nfc tags
2. After some readings the flipper score stop to increase

### Target

RM0715-1017-0.103.2-2c8f998

**Comment by RogueMaster** [comment]
It does go up, crashes may cause issues if it crashes... also, it has it's own rate that it saves

**Comment by Radion94200** [comment]
Furthermore the mood of the dolphin stay the same and never change
What's the solution to back to a normal flow?
