### ISSUE TITLE
[BATTERY] - Battery of the flipper is not representing the real state of the battery

### ISSUE THREAD

**Issue by Radion94200** [RogueMaster/flipperzero-firmware-wPlugins#1078]
### Describe the bug.

The flipper stop working when the battery shows 80 percent of charge and shutdown. If I try to reboot it, the battery level stay at 80 percent but the message on the flipper screen indicate to charge it.

### Reproduction

1. charge flipper
2. use flipper normaly
3. at 80 percent of the battery (show on the flipper) it shutdown
4. reboot the flipper cause the battery indicates 80 percent but charge message appear on the screen

### Target

RM0715-1017-0.103.2-2c8f998

**Comment by RogueMaster** [comment]
Make sure you didn't set a charge cap in CFW Settings

**Comment by Radion94200** [comment]
> Make sure you didn't set a charge cap in CFW Settings

I didn't

**Comment by marki555** [comment]
@Radion94200 this is issue with battery connector, see this reddit post for fix. I had the same issue (flipper shutting down at 30%) and it helped me.
https://www.reddit.com/r/flipperzero/comments/zavpjs/comment/iynzkut/
