### ISSUE TITLE
Flipper Bricked after selecting sword icon from quick panel menu

### ISSUE THREAD

**Issue by FuckingToasters** [RogueMaster/flipperzero-firmware-wPlugins#1082]
### Describe the bug.

So after I selected the swored icon, I got to a screen were I only see small as card icon and battery at the top. Pressing right or left arrow shoes different images but I can't get back to were I were before. I've tried rebooting but it didn't help.

### Reproduction

1. Click on sword icon in Quickmenu Panel
2. See battery icons
3. Reboot
4. Never see the good flipper stuff again (apps, files etc.)

**Comment by FuckingToasters** [comment]
<img width="256" alt="Screenshot-20240729-232919" src="https://github.com/user-attachments/assets/e9fb1d3c-93b0-4bb7-9c46-7b85df20c6f6">

**Comment by RogueMaster** [comment]
Press up to access menu and exit the sword mode, and please don't open an issue for not knowing how to use the flipper. You can search for answers on Discord.
