### ISSUE TITLE
Bluetooth feature BLE spam crashes Flipper zero

### ISSUE THREAD

**Issue by ascalation** [RogueMaster/flipperzero-firmware-wPlugins#1087]
### Describe the bug.

I just got the flipper, so i am not deep into any firmware, therefore haven't checked the code yet and probaply wouldn't understand it anyways.

Just wanted to report what happened to me trying to use the bluetooth features.

Note: i tested with both having my phone connected and without 
          Every other bluetooth feature works

### Reproduction

1. Start Flipperzero
2. Got to the Bluetooth folder
3. Choose BLE spam
4. Start any of the given options

### Target

Bluetooth BLE spammer

### Logs

```Text
Error Message: Flipper crashed and was rebooted - furi_check failed
```

**Comment by lsilentt** [comment]
Same.

**Comment by RogueMaster** [comment]
Will be fixed next release, in the meantime try 50ms
