### ISSUE TITLE
No releases contain *.dfu firmware files

### ISSUE THREAD

**Issue by hasmar04** [RogueMaster/flipperzero-firmware-wPlugins#109]
**Describe the bug**
All of the releases within this repository do not contain the firmware files used to install onto the Flipper. 

**To Reproduce**
1. Visit this repo's releases section
2. Check included files

**Expected behavior**
The dfu files are available to download

**Additional context**
As a side note it would be great if the version release could be added to the update file name.

**Comment by DevMilanIan** [comment]
They were moved with instructions to use the archive app with the unzipped files. These can also be flashed using qFlipper.
