### ISSUE TITLE
Reboots

### ISSUE THREAD

**Issue by refnauj10** [RogueMaster/flipperzero-firmware-wPlugins#1093]
### Describe the bug.

There is a moment when the flipper zero reboots at least 5 times before stabilizing, indicating that the furi load has failed

### Reproduction

1. start a function 
or plugin
2. start a menu feature
3. First start

**Comment by RogueMaster** [comment]
Make sure you have selected an animation set in CFW Settings => Interface => Desktop => Animations

**Comment by RogueMaster** [comment]
Since its having issues pick No Anim

**Comment by refnauj10** [comment]
Well, an the moment this option is on “none” but the reboots persists…

**Comment by Michael-A-Sloan** [comment]
This is still an Issue with mine as well on the latest firmware.

**Comment by Kitt3120** [comment]
Still having the same issue on 0919-0056

**Comment by huuck** [comment]
still happening.
