### ISSUE TITLE
Wrong information in README.md

### ISSUE THREAD

**Issue by derskythe** [RogueMaster/flipperzero-firmware-wPlugins#1094]
### Describe the bug.

Hello @RogueMaster,
Your README.md file contains wrong information about the SubGhz Frequency Analyzer. 
You wrote:

> SubGHz: New frequency analyzer https://github.com/flipperdevices/flipperzero-firmware/pull/1501 [feedback mode (by darmiel)](https://github.com/darmiel/flipper-playlist/tree/feat/stealth-frequency-analyzer) [Quiet Mode (by Himura2la)](https://github.com/ClusterM/flipperzero-firmware/pull/1) https://github.com/flipperdevices/flipperzero-firmware/pull/1557

The current version of the [file](applications/main/subghz/views/subghz_frequency_analyzer.c) does not contain the code of some authors. Also, there is functionality that you did not describe. The links to the PR are also incorrect.

Below are the correct links and functionality:
* Ability to set RSSI trigger level, Sound and vibration on signal detect by @ClusterM (PR [#43](https://github.com/DarkFlippers/unleashed-firmware/pull/43))
* Long press OK button in SubGHz Frequency analyzer switch to Read menu with selected frequency by @DerSkythe (PR [#79](https://github.com/DarkFlippers/unleashed-firmware/pull/79))
* Sync with OFW for brand new interface and improve to 4 elements of history, abillity to disable sound and vibro with saving by @DerSkythe (PR [#121](https://github.com/DarkFlippers/unleashed-firmware/pull/121))
* Add CC1101 module external support by @gid9798 (PR [#534](https://github.com/DarkFlippers/unleashed-firmware/pull/534))
* And many-many bugfixes from @xMasterX

### Reproduction

None

### Anything else?

Have a nice day

**Comment by RogueMaster** [comment]
Thanks for the feedback, the appropriate application.fam will be updated, however, please note:

These changes  [New frequency analyzer #1557 (By ClusterM)](https://github.com/flipperdevices/flipperzero-firmware/pull/1557) were here far before they were taken from the UL PR. This PR predates the UL PR.

Also, [feedback mode (by darmiel)](https://github.com/darmiel/flipper-playlist/tree/feat/stealth-frequency-analyzer) and [Quiet Mode (by Himura2la)](https://github.com/ClusterM/flipperzero-firmware/pull/1) (Link Dead) ideas were taken and used by OFW and merged with no credit here: [Sync with OFW for brand new interface and improve to 4 elements of history, abillity to disable sound and vibro with saving (By derskythe)](https://github.com/DarkFlippers/unleashed-firmware/pull/121) These features were in RM far before they were merged into UL and OFW and proper credit will remain given for the creators for these ideas/features.
