### ISSUE TITLE
plugins highlighted with ELF not seen in the plugin menu

### ISSUE THREAD

**Issue by amiseh** [RogueMaster/flipperzero-firmware-wPlugins#110]
Guys,

can You tell me what should I do to see all the plugins which are included in this firmware on my flipper?? I can see only few of them link:
- HID analyzer
- PicoPassReader
- TOTP
- Wifi scanner

so the plugins without ELF highlight/information before the name of the plugin... 

![image](https://user-images.githubusercontent.com/82850484/180412941-332acce0-5656-4439-88cc-19899a12de33.png)

what to do to make rest of them visible and working?

**Comment by xNymia** [comment]
The rest of these plugins are ELF binaries and are available under the ELF Loader main menu option.

**Comment by amiseh** [comment]
ok, found out what was wrong. had to manually put apps folder onto SD card and just after that was able to run application with EFL loader. 

sorry. it was my mistake.
