### ISSUE TITLE
Question about implementations of 1.0 firmware

### ISSUE THREAD

**Issue by Xbxjdjdjd** [RogueMaster/flipperzero-firmware-wPlugins#1100]
Will the features like long battery life and extended nfc on the stock 1.0 firmware be added to RM?

**Comment by RogueMaster** [comment]
Yes, since long long ago, please do keep better up to date with flipper updates and when features actually get added to the firmware before opening senseless issues...

**Comment by Xbxjdjdjd** [comment]
Sorry for wasting your time
