### ISSUE TITLE
When opening NFC, flipper crashes, and reboots with error message “BusFault”

### ISSUE THREAD

**Issue by Xbxjdjdjd** [RogueMaster/flipperzero-firmware-wPlugins#1101]
### Describe the bug.

When opening the main nfc app, the flipper crashes and reboots with the message “BusFault”

### Reproduction

1. Turn on flipper
2. Click the center button to access the features
3. Scroll to NFC
4. Click NFC
5. The flipper will crash, restart, and say “BusFault”

### Anything else?

I am very, truly, genuinely sorry if this is my fault or it’s already been worked on. I have a video of it happening [here](https://imgur.com/a/YvK2Lsq)

**Comment by RogueMaster** [comment]
This is a known issue being looked into, in the meantime, please open a PR if you find a fix...
