### ISSUE TITLE
NFC Read function occures an error, flipper restart

### ISSUE THREAD

**Issue by toby0683** [RogueMaster/flipperzero-firmware-wPlugins#1102]
Hi,
I have always had the same problem for many updates: When I select the NFC read function, my FZ crashes. He performs a reboot. Messages are: Bus fault, Memory error, not enough memory etc. Sometimes it allows the read function, but at the latest when I want to read an NFC card, the FZ crashes again. I tried it independently on another FZ. I bought a new SD card, which is required by LAB401. I don't know what to do. Is this bug known or can the source of the error be checked again? Does anyone have a tip from experience? Maybe I'm not the only one. Kind regards, Toby.

**Comment by RogueMaster** [comment]
See if latest changes have fixed your issue
