### ISSUE TITLE
Blank Browser screen since last update

### ISSUE THREAD

**Issue by TonyStark02** [RogueMaster/flipperzero-firmware-wPlugins#1103]
### Describe the bug.

Hello,

Since the last update my app browser displays nothing(when I click the center button).

Tried to reinstall but still the same.

### Reproduction

Click the center button to access the apps browser

**Comment by RogueMaster** [comment]
Please re-install using web installer method, this is not an issue in the firmware

**Comment by TonyStark02** [comment]
Hello,

I already reinstalled with the web installer but still the same. Then I tried to reinstall the stock firmware, and that works well so it looks like more a bug :/
