### ISSUE TITLE
flipperzero region file missing

### ISSUE THREAD

**Issue by KF5HKI** [RogueMaster/flipperzero-firmware-wPlugins#1109]
### Describe the bug.

After updating flipper zero to "RM1111-1406-0.420.0-243c618" it was showing region file missing for sub-GHz files, it was working fine on "RM1103-2222-0.420.0-b2f8dce"

### Reproduction

Send any Sub-GHz file with firmware RM1111-1406-0.420.0-243c618

**Comment by RogueMaster** [comment]
Will check into this, if you bypass region the firmware will work as intended

**Comment by KF5HKI** [comment]
I just updated to the "RM1119-2303-0.420.0-0872731" and it still has the region file missing issue, so as a test I updated to the flipper 1.1.2 firmware and it works and shows region as US.
So then I updated back to RM1119-2303-0.420.0-0872731 and it says region file missing.

If there is anything else I can do to help with this let me know.

**Comment by Crashkeyz** [comment]
Same here

**Comment by Crashkeyz** [comment]
Same here

**Comment by RogueMaster** [comment]
See last line of the error and follow directions appropriately

**Comment by tyizhere** [comment]
Seeing this bug again on version 42 new install

**Comment by mithrandir42** [comment]
Using the SubGhz Bypass in CFW setings of course works. But this unlocks all frequencies, not just the ones legal in the region. Reinstalling via Web or qFlipper as suggested by the error message does not solve the problem. Afterwards the region file error still is there.

Same region file is in SD Card/.int/.region_file and Internal Flash/.region_file:
hexdump -C .region_data 
00000000  0a 02 44 45 12 10 08 90  a3 bf ce 01 10 f0 bc a9  |..DE............|
00000010  cf 01 18 0c 20 32 12 10  08 f0 d5 fb 9d 03 10 f0  |.... 2..........|
00000020  8a 94 9e 03 18 0c 20 32                           |...... 2|
00000028

This is on current RM0226-1517-0.420.0-847b104 .
