### ISSUE TITLE
The elf loader is not working properly

### ISSUE THREAD

**Issue by Hyralc** [RogueMaster/flipperzero-firmware-wPlugins#111]
When y use the elf loader, i always get an error:
Error: load failed: 3

It does this on every single one elf file

**Comment by RogueMaster** [comment]
Did you install using readme instructions and the archive app?

**Comment by Hyralc** [comment]
i followed the instructions here: https://flipper.pingywon.com/
i downloaded the whole archive containing everything and put it in the right place, and the files thas goes to subgz/assets too

**Comment by Hyralc** [comment]
maybe the resources there are outdated ?

**Comment by RogueMaster** [comment]
That's not my page and I don't suggest installing with DFU. Please use the readme

**Comment by Hyralc** [comment]
ok i corrected it, thanks and sorry
