### ISSUE TITLE
furi_check failed

### ISSUE THREAD

**Issue by MUAK47** [RogueMaster/flipperzero-firmware-wPlugins#1110]
### Describe the bug.

I recently installed the Rogue Master Firmware, and whenever I turn my Flipper on, it says furi_check has failed. The animations that come with Rogue Master Firmware also dont load, Im left with a blank screen. My manifest.txt files are all intact and working when I use the normal Flipper Software.

### Reproduction

1. Switch on/Reboot
2. Wait a while
3. Flipper Reboots
4. furi_check has failed
5. Press ok
6. The Animations are gone, but the flipper works fine.

### Anything else?

Does anyone have a similar problem or a solution?

**Comment by RogueMaster** [comment]
Any extra files in your dolphin folder?
