### ISSUE TITLE
Unable to connect to flipper with iPhone once firmware is installed

### ISSUE THREAD

**Issue by Billy13723** [RogueMaster/flipperzero-firmware-wPlugins#1111]
### Describe the bug.

Have tried forgetting the device, restarting the device and restarting both devices. 

### Reproduction

Download firmware and try to connect phone 

### Target

Connection of phone

**Comment by RogueMaster** [comment]
You may want to unpair on flipper and phone and try again. After getting some time to test it, it connects just fine on iPhone.
