### ISSUE TITLE
[app] Orgasmotron locks up Flipper

### ISSUE THREAD

**Issue by headcase0570** [RogueMaster/flipperzero-firmware-wPlugins#1115]
### Describe the bug.

Looking through all the apps I opened Tools>Orgasmotron to see what it was. After spamming the button a few times I tried closing the app by pressing the back key but the interface no longer responded. It's as if it's going through a list of queued actions, so much that new input/navigation was not possible. 
After a few seconds the Flipper froze entirely, I had to take out the SD card and hold all buttons for 30 seconds to force it to restart.

### Reproduction

1. switch on
2. go to apps
3. go to tools
4. find 'Orgasmotron'
5. spam the buttons for a bit
6. ???
7. Have a bad time.

### Target

Orgasmotron

### Logs

```Text
No logs available, formatted my SD card for a fresh RM install
```

### Anything else?

I LOVE ROGUEMASTER!

**Comment by RogueMaster** [comment]
Glad you love the firmware, this app works as intended, if you don't spam the buttons too much it will continue to work. Not intending to work on this app.
