### ISSUE TITLE
RM Web Installer issue(s)

### ISSUE THREAD

**Issue by headcase0570** [RogueMaster/flipperzero-firmware-wPlugins#1117]
### Describe the bug.

The issues below are intermittent, it won't happen every time but every once in a while.
Sometimes when I connect my Flipper to the Flipper Labs (https://lab.flipper.net) I get an error shown on the bottom-right of the screen: **RPC error in command 'storageRename': RPC timeout: storageRenameRequest**
This will also happen when using the left-hand navigation menu to go to 'Files', it'll say 'Waiting for Flipper' for a while before throwing the error: "**RPC error in command 'storageList': RPC timeout: storageListRequest**
". All other menu options work just fine, My Flipper, Apps, CLI, etc. These all work.

Maybe not a bug? In Flipper Lab I'll go to Apps, wait until the list refreshes and I can see some apps' status shown as 'INSTALLED'. When I go to the 'INSTALLED' menu, located right-side of the search bar, the menu will be empty with the text: "**You haven't installed any apps yet**"  will be shown. Screenshots added.
<img width="1425" alt="Screenshot 2024-12-03 at 13 17 01" src="https://github.com/user-attachments/assets/971a34a2-9b20-4d38-8c85-56d997b1649f">

I am using Google Chrome (Version 131.0.6778.86 (Official Build) (x86_64)

<img width="1430" alt="Screenshot 2024-12-03 at 13 17 09" src="https://github.com/user-attachments/assets/b21550f5-aff4-48df-927b-39e73a7ea6a6">

### Reproduction

1. Go to https://lab.flipper.net/
2. Connect Flipper
3. See first error: **RPC error in command 'storageRename': RPC timeout: storageRenameRequest**
4. Go to 'Files'
5. Get second error: **RPC error in command 'storageList': RPC timeout: storageListRequest**
6. Go to Apps, install an app
7. Go to Installed, see no apps are installed
8. Go to https://github.com/RogueMaster/ 
9. Post Bugreport
10. Have coffee

### Target

Web Installer

### Logs

```Text
13:37:1 [INFO] Main: Flipper connected
13:37:2 [INFO] Main: RPC started
13:37:2 [DEBUG] Main: propertyGet: OK
13:37:2 [DEBUG] Main: propertyGet: OK
13:37:2 [DEBUG] Main: storageList: /ext
13:37:2 [DEBUG] Main: storageInfo: /ext
13:37:2 [DEBUG] Main: storageInfo: /int
13:37:2 [INFO] Main: Fetched device info
13:37:2 [DEBUG] Main: systemSetDatetime: OK
13:37:3 [DEBUG] Device: guiStartScreenStream: OK
13:37:6 [INFO] Main: Flipper has been disconnected
13:37:15 [INFO] Main: Flipper connected
13:37:31 [ERROR] Main: Error while starting RPC: RPC timeout: systemPingRequest
13:37:31 [INFO] Main: RPC started
13:37:46 [ERROR] Device: RPC error in command 'guiStopScreenStream': RPC timeout: guiStopScreenStreamRequest
13:37:46 [DEBUG] Device: guiStopScreenStream: OK
```

### Anything else?

Sorry for spamming bugreports, doing my part in making RM just a tiny bit better

**Comment by RogueMaster** [comment]
All apps come with firmware, the app installer there does not get used
