### ISSUE TITLE
Android or Iphone app, sub-ghz not sending on Flipper. Error since end of August

### ISSUE THREAD

**Issue by Kzy07** [RogueMaster/flipperzero-firmware-wPlugins#1118]
### Describe the bug.

With Android or Iphone App, sub-ghz commands are not sent to Flipper.

### Reproduction

1 - select sub-ghz archive in app
2 - click send
3 - flipper not run

### Target

Flipper

**Comment by RogueMaster** [comment]
After getting some time to test on iphone, it connects just fine on iPhone and sends file.
