### ISSUE TITLE
NFR Jammer Doesn´t Work with multiboard 3 in 1 (ESP32, CC1101, NFR24)

### ISSUE THREAD

**Issue by refnauj10** [RogueMaster/flipperzero-firmware-wPlugins#1119]
### Describe the bug.

I have the 3 in 1 multi card which has the NFR24 module, ESP32 and CC1101, I have just updated to the latest version and although I have followed the steps, the jammer does not work, the audio is still running.

### Reproduction

1. Select Board in NFR24 and select TX.
2. Enter the NRF24 jammer application.
3. Select between narrow, wide or full options.
4. Press ok

### Target

NFR24,JAMMER,AUDIO

**Comment by RogueMaster** [comment]
You've mistaken this repository. We are not the repository for this app nor for your board.
