### ISSUE TITLE
Flipper crashed and was rebooted HardFault 

### ISSUE THREAD

**Issue by quarac** [RogueMaster/flipperzero-firmware-wPlugins#119]
### Describe the bug.

The title of the issue is the message I see on the Flipper screen every time I try to send this saved signal:
[S202207271401.sub.zip](https://github.com/RogueMaster/flipperzero-firmware-wPlugins/files/9199578/S202207271401.sub.zip)

It was recorded from my garage door remote, with the read function in subghz, at 868.35 AM270, hopping OFF, detect RAW OFF

I’m using firmware CA5D0963 (25 Jul 2022)
My hardware version: 12.F7B9C6
Radio FW: 1.13.3 LIT

### Reproduction

Add the attached file to your flipper and try to send it.

**Comment by RogueMaster** [comment]
Pushed some fixes that hopefully fix it on next build...
