### ISSUE TITLE
Add/Modify   frequency to setting_user is not effective

### ISSUE THREAD

**Issue by PeterCheungHK** [RogueMaster/flipperzero-firmware-wPlugins#120]
### Describe the bug.

I Try to Add/Modify  frequency on setting_user 
[setting_user ](https://github.com/PeterCheungHK/demo/blob/master/setting_user ), but the Sub-Ghz >Read and read RAW > Frequency an not effective( i disable 300Mhz And Add 409Mhz)

### Reproduction

1. Add or Modify frequency  on setting_user, that reboot
2. Select Sub-Ghz
3. Choose Read or Read RAW , Press < to Config 
4. Your add /disable frequency   still on the list

**Comment by RogueMaster** [comment]
300 works for me after changing setting_user... please recheck that you change needed files after updating via SD

**Comment by PeterCheungHK** [comment]
> 300 works for me after changing setting_user... please recheck that you change needed files after updating via SD

My mistake , lastly i copy all resources.tar to SD card is fixed

**Comment by koromar** [comment]
I have the same problem. Besides the hopping issue, 'ignore_default_tx_region' is being ignored as well for me.
Flashed the latest (-0727-RM) two times in total, SD was formatted and filled with `resources.tar` from -0727-RM; I only edited `subghz/assets/setting_user` with no effect.
