### ISSUE TITLE
Game_Arkanoid is crashed in FW:0727  when press Back button

### ISSUE THREAD

**Issue by PeterCheungHK** [RogueMaster/flipperzero-firmware-wPlugins#121]
### Describe the bug.

Game_Arkanoid is crashed in FW:0727  when pressing the Back button

### Reproduction

1. FAP Loader
2. Select Game_Arkanoid
3. press the Back button
4. Flipper crashed and was rebooted HardFault

**Comment by RogueMaster** [comment]
Yes, it does that

**Comment by PeterCheungHK** [comment]
not work for me😭same file in 0.62.3-0725-RM is ok , can you check again ?
Thank you
