### ISSUE TITLE
BadUSB types wrong characters

### ISSUE THREAD

**Issue by g1lby** [RogueMaster/flipperzero-firmware-wPlugins#124]
Hi there,

I just noticed, that if I'm running a BadUSB payload on my testing machine, most of the special characters typed are incorrect.

My testing machine is a MacBook Pro with German keyboard layout.
I tried the "Char_Test" and "Char_Test_ALTSTRING" payload from UberGuidoZ on my FlipperZero which I've just flashed before.

The output from those payloads is as follows:

 "Char_Test_ALTSTRING"

` 59 Semicolon `
` 44 Comma `
` 60 Less than `
` 62 Greater than `
` 46 Period `
` 63 Question mark `
` 47 Forward slash `
` 92 Backslash `
` 91 Left bracket `
` 93 Right bracket `
` 42 Asterisk `
` 40 Left parentheses `
` 41 Right parentheses `
` 124 Pipe `
` 126 Tilde `

"Char_Test"

` ö Semicolon `
` , Comma `
` ; Less than `
` : Greater than `
` . Period `
` _ Question mark `
` - Forward slash `
` # Backslash `
` ü Left bracket `
` + Right bracket `
` ( Asterisk `
` ) Left parentheses `
` = Right parentheses `
` ' Pipe `
` > Tilde `

Done for now! )Created bz UberGuidoY=
httpsÖ--github.com-UberGuidoY-Flipper

From what I read here https://www.reddit.com/r/flipperzero/comments/vz4cb9/badusb_displaying_as/ I assumed that it might have something to do with your firmware and that it should have worked with ALTSTRING (which unfortunately didn't) - is that correct?

Cheers,
g1lby

**Comment by RogueMaster** [comment]
Yup, doesn't work on German keyboard. Known issue. There is a project that will allow for DUCKY LANG that may get merged.
