### ISSUE TITLE
Add Comma to keyboard

### ISSUE THREAD

**Issue by edrethardo** [RogueMaster/flipperzero-firmware-wPlugins#128]
### Describe the enhancement you're suggesting.

As it's useful for Marauder Wifi to add multiple aps to attack with one select command I'd propose to add the comma (',') to the right of the '_' character. Thr eresult would look like in the attached gif
![Keyboard with Comma](https://user-images.githubusercontent.com/47067768/181643052-c99282fd-47dd-4e37-99d7-c5b502bf8dc3.png)

**Comment by RogueMaster** [comment]
Please make this request with main FW or the person who made the Marauder companion.
