### ISSUE TITLE
Clock app should follow system settings for volume

### ISSUE THREAD

**Issue by danielskowronski** [RogueMaster/flipperzero-firmware-wPlugins#131]
### Describe the enhancement you're suggesting.

Currently, clock app emits sounds even when system volume setting is set to 0%. 

If changed to follow system settings, it would greatly improve stealth mode, since it's easy to press enter button, which starts the stopwatch - on every restart of the app, it reverts to default sound settings (Mario).

Behaviour present on 0.63.2-0728-RM-Tv2 and 0.62.3-0725-RM

**Comment by RogueMaster** [comment]
Yes, you are absolutely correct; it should. Would you like to look into assigning those settings? @danielskowronski

**Comment by danielskowronski** [comment]
I can try :)

**Comment by Ganapati** [comment]
PR with a patch : https://github.com/RogueMaster/flipperzero-firmware-wPlugins/pull/246

**Comment by RogueMaster** [comment]
Fixed by Ganapati
