### ISSUE TITLE
Flipper crashing after SD Card unmount

### ISSUE THREAD

**Issue by Painkiller8818** [RogueMaster/flipperzero-firmware-wPlugins#146]
Newest FW 0.63.3-0801-RM-LVLS is crashing flipper after unmounting SD Card and clicking back to flipper menu

**Comment by RogueMaster** [comment]
After install? Readme warns this would happen... or is it under different circumstances?

**Comment by Painkiller8818** [comment]
No, everytime you unmount the SD. The Update was successful and works --Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 01.08.22, 13:20 schrieb RogueMaster ***@***.***>:

   
  After install? Readme warns this would happen... or is it under different circumstances?
