### ISSUE TITLE
BadUSB: DUCKY_LANG not working

### ISSUE THREAD

**Issue by gilfy** [RogueMaster/flipperzero-firmware-wPlugins#149]
### Describe the bug.

I am adding DUCKY_LANG DE to the first or the second raw and the payload is still in default

### Reproduction

Switch you keyboard setting to DE and execute the payload via Flipper

**Comment by RogueMaster** [comment]
Please let me know as you test how you come to a solution

**Comment by RogueMaster** [comment]
Try it exclusively on line 1 and let me know if it fixes it

**Comment by gilfy** [comment]
As I already mentioned exclusively line 1 or line 2 does not work unfortunally :(

**Comment by carnyccc** [comment]
Hi I had the same problem and was able to solve it by changing the script file in Notepad++ from Windows CR/LF to Unix LF.

**Comment by gilfy** [comment]
Ya @carnyccc but this is not the goal to set smth by your own. Imagine you have a PC of your friend etc. you cannot setup first his PC :D

**Comment by RogueMaster** [comment]
> Hi I had the same problem and was able to solve it by changing the script file in Notepad++ from Windows CR/LF to Unix LF.

Thank you for the solution 😄
