### ISSUE TITLE
Unable to change default name in SAVE RAW

### ISSUE THREAD

**Issue by Eng1n33r** [RogueMaster/flipperzero-firmware-wPlugins#15]
**Describe the bug**
Unable to rename raw filename.

**To Reproduce**
1. Save some raw signal
2. Try to change defualt name
3. See error with sd-card icon (cant rename)
4. Thats it.

**Expected behavior**
Saving with changed name as it should be.

**Target**
F7

**Additional context**
In my unleashed fork I will try make temp solution for it.

**Comment by Eng1n33r** [comment]
Seems to be fixed in new update allready. Or it is SD card bug. I have saved 3 signals with changed name, but 4th gave same error. But renaming existing file is allways OK. Very strange...

**Comment by RogueMaster** [comment]
Maybe SD bug, I tried to recreate and it renamed properly. I'm using a 128GB SD card from Brands Mart. Forgot the brand and my SD card is taped in.

**Comment by Eng1n33r** [comment]
> Maybe SD bug, I tried to recreate and it renamed properly. I'm using a 128GB SD card from Brands Mart. Forgot the brand and my SD card is taped in.

Mine is also 128GB. SanDisk Ultra XC I
Fortunatly, bug is no longer appears.
