### ISSUE TITLE
Hardfault when read new mail

### ISSUE THREAD

**Issue by onelezarman** [RogueMaster/flipperzero-firmware-wPlugins#150]
### Describe the bug.

When I click left on the new mail for pass to the lvl 7  flipper reboot and hardfault 

### Reproduction

1 press left for read new mail
2 reboot and hardfault

### Target

0.63.3-0801-RM-LVLS

**Comment by RogueMaster** [comment]
Hard fault and it boots up again or does it reboot infinitely?

**Comment by onelezarman** [comment]
First time after the update he reboot indefinitely 
So I'm turn it to dfu mode and put all file on the update folder for reupdate and now on read mail he just reboot crash but after I can use it is boot up again

**Comment by RogueMaster** [comment]
Ok I'll try to force my flipper to level and test out if I can recreate. Did you do the update with SD card? You need the updated dolphin/manifest.txt file for levels over 3 but I also haven't tested leveling on higher than 3

**Comment by onelezarman** [comment]
I did not modify the manifest it must probably come from here
And yes I update with SD
before the update I was close to level 3 and after the update I went to lvl 6 with the same amount of xp and I received the mail for lvl 7

**Comment by onelezarman** [comment]
The manifest is good
![20220802_001318.jpg](https://user-images.githubusercontent.com/9158423/182254644-88e35b0c-d616-4d7f-a3fc-37cd7bc07c0a.jpg)

**Comment by onelezarman** [comment]
https://user-images.githubusercontent.com/9158423/182255414-0df81e46-0ad9-401f-bf4e-750a831b85ee.mp4

**Comment by RogueMaster** [comment]
Could you compile and test current build to see if new mail causes fault?

**Comment by RogueMaster** [comment]
Confirmed this is fixed

**Comment by onelezarman** [comment]
that good after your morning update thanks
