### ISSUE TITLE
Sub-ghz auto read crash

### ISSUE THREAD

**Issue by FrozenGhostx** [RogueMaster/flipperzero-firmware-wPlugins#157]
### Describe the bug.

When you navigate to sub ghz, select auto read and select in options "detect raw", scan on 433.88MHz  and AM650 Emulation and search for keys, it finds them and you can select them. If you try to click on one of the found keys, flipper crashes and can't boot up anymore. Goes in DFU, you just can re-flash it.

### Reproduction

SubGHZ
Read
Detect RAW
Found Keys
Select them
Crash
Destroyed (just kiddin'. DFU.)

**Comment by FrozenGhostx** [comment]
EDIT: Re-Tried, as soon as i try to replay the detected raw, it fully crashes and can't boot up anymore.

**Comment by Einstein2150** [comment]
Tried at 434.42 AM650 Raw Detection on - no Problem while scanning, saving and replaying here ... 🤷🏻‍♂️

**Comment by FrozenGhostx** [comment]
> Tried at 434.42 AM650 Raw Detection on - no Problem while scanning, saving and replaying here ... 🤷🏻‍♂️

Tried on 433.88 and 433.92? These both crashes. Already re-flashed it 3 times to be sure.

**Comment by perspecdev** [comment]
There's a bug where if you click the Send button before saving the signal, it will crash.

**Comment by RogueMaster** [comment]
This option was fixed on #160
