### ISSUE TITLE
SubFrequenzy - Read / reply RAW crashes flipper

### ISSUE THREAD

**Issue by thespawnat** [RogueMaster/flipperzero-firmware-wPlugins#161]
### Describe the bug.

I've installed the latest FW-Update today morning. 

I'm running the SubGhz in Read with Settings: Hopping = ON ; Modulation = AM650 ; Detect Raw = ON.

the sniffer works and creates the entries in the list. When I open an entry and emulate, the flipper screen goes off and is unresponsive. with "left + back" (soft reset) it gets back to life and provides an error message about hard fault

### Reproduction

install latest FW
open SubGhz
open Read
set to "hopping = true" 
set to "Modulation = AM650"
set to "Detect RAW = true"
start sniffing
once entry appears -> open it and press "emulate"
-> flipper crashes

### Target

0.63.4-0802-RM-LVLS [Latest](https://github.com/RogueMaster/flipperzero-firmware-wPlugins/releases/latest)

**Comment by RogueMaster** [comment]
Will emulating after a flipper restart still cause a bug/crash?

**Comment by thespawnat** [comment]
If the file is saved and opened via subghz/saved I can emulate it properly.

If I save it and directly try to emulate from 'read-mode' it crashes too (blank screen, no led, no response)

I just checked the files and all of them are raw-capture-files

**Comment by RogueMaster** [comment]
@perspecdev Could emulate from read-mode be fixed or disabled? Thank you for your help!

**Comment by tim427** [comment]
I can indeed confirm that the flipper crashes from "read" and directly "replay".

Saving and "replay" from "saved" works just fine.

**Comment by perspecdev** [comment]
Thanks for this.  Is there a new "emulate" button?  As far as I know, there was only "send" button, and I disabled it with the latest PR, but maybe I'm not on the latest code.  I'll update everything in a bit and take a look.

**Comment by onelezarman** [comment]
Hello I have the same issue 🙃

**Comment by av4k1r** [comment]
After captured with the "RAW" option,when "SEND" is pressed, it restarts and "Hard fault" is displayed

**Comment by av4k1r** [comment]
After capturing with "RAW" option and pressing the "SEND", the Flipper freeze. I had to press "left & back" to reboot, it displays "NULL pointer dereference"

**Comment by Mika73** [comment]
Just updated to latest firmware. Now when trying to read wireless carkey Flipper crash and reboot everytime.

**Comment by thespawnat** [comment]
installed latest update today morning. Behavior is the same as with FW from yesterday with "Send" crashes FZ in "read"-mode (nullpointer reference). 
 when I try "read" with RAW capture enabled I'm unable to detect my car key on 868,35. if I make a "read raw" on the same Frequenz, I'm able to capture the signals and send them directly from "read raw" without reboot / freezes

**Comment by Mika73** [comment]
I managed read wireless Car key with hopping mode and save it. But when try send it/emulate Flipper did crash. And had difficulty turn it back on.

**Comment by RogueMaster** [comment]
This should be fixed on last release
