### ISSUE TITLE
Add GFSK to SubGHZ

### ISSUE THREAD

**Issue by Mik13** [RogueMaster/flipperzero-firmware-wPlugins#162]
### Describe the enhancement you're suggesting.

There should be a possibility to read and save chats done on the cli (subghz chat).

I already found out it uses the GFSK modulation which furi knows, but the subghz application is missing.

### Anything else?

I tried my luck, but it does not work:
https://github.com/RogueMaster/flipperzero-firmware-wPlugins/commit/f7c128cb5861b4b35bbe3c1355d359015d482740

When using Read RAW with GFSK and the correct frequency. the flipper receives the message (when using another flipper and sending a message there), spl goes to 2 and the bar goes up, but never down as it should. Stopping recording and sending does nothing (aka, the flipper in chat does not receive anything).

Could you point me at the correct direction about what I am missing? Thank you in advance!

**Comment by Mik13** [comment]
Sadly I can't work on this issue very much because I only own one flipper and no SDR or other device to send chat messages from to my flipper.

**Comment by RogueMaster** [comment]
I can't help you with this request; perhaps submit it upstream to see if they can help
