### ISSUE TITLE
Flipper FW Version not raising after successful update

### ISSUE THREAD

**Issue by Painkiller8818** [RogueMaster/flipperzero-firmware-wPlugins#164]
### Describe the bug.

Updating the Flipper over the local update folder seems not to work.
As the flipper tells me the update was successful it is still showing 0.63.3 instead of 0.63.4, not sure if the update was not working or if you forgot to raise the versions info

### Reproduction

1. load the new update in the update folder of SD
2. insert SD into flipper and run the local update
3. check the version after a successful update, it still shows the prev. version

**Comment by RogueMaster** [comment]
if you compile from code, this would be fixed. It was only a problem on latest release.
