### ISSUE TITLE
Bad USB crash

### ISSUE THREAD

**Issue by neoteknic** [RogueMaster/flipperzero-firmware-wPlugins#177]
### Describe the bug.

Open bad USB (no menu for keyboard config ?) 
crash when back button is pressed

### Reproduction

Open bad USB
 press back = crash null pointer reference

### Target

0.63.4-0804-RM-R2

**Comment by ramondunker** [comment]
I'm seeing the same behaviour when trying to capture the signal of my garage door fob. Also shows a null pointer reference.

**Comment by RogueMaster** [comment]
This was fixed by latest changes
