### ISSUE TITLE
Read Sub-Ghz does still crash 

### ISSUE THREAD

**Issue by Mika73** [RogueMaster/flipperzero-firmware-wPlugins#179]
### Describe the bug.

Updated to latest Flipper firmware. Read Sub-Ghz does still crash Flipper.

I can read if use hopping mode but when try send Flipper does crash. 

### Reproduction

Read Sub-Ghz crash flipper. 

### Target

Sub-Ghz read crash

**Comment by RogueMaster** [comment]
Please try on the latest release "TAMA" coming out
