### ISSUE TITLE
Frequency Analyser keeps detecting a non existent signal at 468.000 MHz

### ISSUE THREAD

**Issue by aaronrolls** [RogueMaster/flipperzero-firmware-wPlugins#185]
### Describe the bug.

The frequency analyser keeps detecting a signal at 468.000 MHz. It detects it about every 3 seconds.

However when I try to read the raw signal at that frequency, I get nothing at any modulation.

### Reproduction

Open the Frequency Analyser and wait for it to detect the fantom signal

### Target

0.63.4[05-08-2022]

**Comment by RogueMaster** [comment]
Please update with SD update to get rid of the phantom frequency
