### ISSUE TITLE
nrfsniff crashing

### ISSUE THREAD

**Issue by mfulz** [RogueMaster/flipperzero-firmware-wPlugins#192]
### Describe the bug.

Starting nrf sniff with or without nrf24 module attached gives a hard fault crash.

### Reproduction

1. Start NRF SNIFF
2. Press Enter

### Target

[0.63.5-0806-RM-NOFAP](https://github.com/RogueMaster/flipperzero-firmware-wPlugins/releases/tag/0.63.5-0806-RM-NOFAP)

**Comment by RogueMaster** [comment]
Seems to work with one... without one no doubt it could crash... it needs the module
