### ISSUE TITLE
SubGHz outside default range... Å

### ISSUE THREAD

**Issue by L0rdS474n** [RogueMaster/flipperzero-firmware-wPlugins#197]
### Describe the bug.

Not sure if this is a bug or that some settings moved...

Have extended range activated and ignore default TX region activated.
For the last three or so FW this file does not work, claims that range is outside default range, why is it outside default range?

https://raw.githubusercontent.com/UberGuidoZ/Flipper/945362d3a8058f082abd7e6dbe57864d95d363f8/Sub-GHz/Restaurant_Pagers/LRS_Pagers/BruteForceRest.sub

### Reproduction

1. Switch on
2. Go to SubGHz
3. Load the file https://raw.githubusercontent.com/UberGuidoZ/Flipper/945362d3a8058f082abd7e6dbe57864d95d363f8/Sub-GHz/Restaurant_Pagers/LRS_Pagers/BruteForceRest.sub
4. It will show that this is outside the range

### Target

Latest RougeMaster FW

### Anything else?

Everything for extended range is activated and all frequencies are in setting_user file

Worked for 3 before the last 3 firmwares

**Comment by RogueMaster** [comment]
Ok I tested and can confirm something is up with it. Will review

**Comment by RogueMaster** [comment]
Fixed on commit 28317ca710c1cd31e2ba4a15d10b21740071824a

**Comment by L0rdS474n** [comment]
This bug is back again since today

**Comment by marcstae** [comment]
I have the same problem
