### ISSUE TITLE
Wrong date clock

### ISSUE THREAD

**Issue by Foul** [RogueMaster/flipperzero-firmware-wPlugins#201]
### Describe the bug.

When linked/synced to the PC APP, date clock is ok.
When linked/synced to the Android APP, date clock is wrong.
![IMG_20220808_012420](https://user-images.githubusercontent.com/829842/183315245-440915d8-18e3-4c49-8b38-8bdfcfb136de.jpg)

### Reproduction

Switch on your flipper zero
Sync the Android APP via Bluetooth
Check your date/year under Clock App !
(day/month are good)

### Target

Clock App ?

**Comment by RogueMaster** [comment]
Sorry, this must have something to do with a wrong clock somewhere getting synced in... I don't know how to fix it nor do I have the issue since my devices sync the right date/time... I would say re-sync with PC to try to fix your issue...
