### ISSUE TITLE
Getting out of "game only" mode

### ISSUE THREAD

**Issue by SeeDborg** [RogueMaster/flipperzero-firmware-wPlugins#211]
### Describe the bug.

I turned on yesterday the "game only" mode and I can't get out of it. Could you help me please ?
Regards.

### Reproduction

Turn on game mode

**Comment by somebirby** [comment]
Refer to the README to exit Game Mode:
UP UP DOWN DOWN LEFT CENTER LEFT CENTER FOR MAIN MENU
