### ISSUE TITLE
Opening /ext/subghz/assets/extend_range.txt crashes Flipper or causes a hang

### ISSUE THREAD

**Issue by zviratko** [RogueMaster/flipperzero-firmware-wPlugins#214]
### Describe the bug.

After updating to today's version (0.63.5-0809-RM-V3), opening /ext/subghz/assets/extend_range.txt via the iOS Flipper app crashed the Flipper (HardFault).
Browsing and syncing seems to work fine.
Sometimes it just causes a timeout (Session closed) but Flipper crashes when any button is pressed.

It worked fine on previous update.

### Reproduction

Update to 0.63.5-0809-RM-V3
Try to edit extend_range.txt via iOS app

### Target

0.63.5-0809-RM-V3

**Comment by RogueMaster** [comment]
this is related to a bug on main about ios app opened yesterday

**Comment by zviratko** [comment]
Thanks.
Do you want issues like this reported here or should I take it upstream next time? (and what is upstream - unleashed or OFW? :))
