### ISSUE TITLE
Crash during syncronization by bluetooth with the Flipper App on iOS

### ISSUE THREAD

**Issue by Mareg74** [RogueMaster/flipperzero-firmware-wPlugins#216]
### Describe the bug.

When I try to syncronize the Flipper with the iOS app it'll crash the flipper, reboot it and show me this message

### Reproduction

1. Open iOS app
2. Connect to your Flipper
3. After starting syncronization with the app the flipper will crash and restart
![IMG_2918](https://user-images.githubusercontent.com/110972711/183979057-d311f711-504f-479d-94de-dd778160b0f9.jpg)

### Target

0.63.5-0809-RM-V3

### Anything else?

Tested on an other new Flipper and other phone (my brother's one) still the same problem

**Comment by RogueMaster** [comment]
https://github.com/flipperdevices/flipperzero-firmware/issues/1570

**Comment by onelezarman** [comment]
Have the same issue on android
