### ISSUE TITLE
Spectrum Analyzer Crash/Brick

### ISSUE THREAD

**Issue by tacodestroyer** [RogueMaster/flipperzero-firmware-wPlugins#217]
### Describe the bug.

After updating to the latest version of Unleashed, I went to the Spectrum Analyzer and it picked up a few signals, then the entire Flipper shut off and won't come back on. It was fully charged prior to this.

### Reproduction

1. Power on
2. Go to Spectrum Analyzer
3. Monitor for frequencies
4. Click the left and right arrow to adjust whatever that setting is
5. Crash

**Comment by RogueMaster** [comment]
This isn't unleashed though... have you tested it in RM?
