### ISSUE TITLE
Sub-Ghz - Lock keyboard do not work

### ISSUE THREAD

**Issue by miha-perfecto** [RogueMaster/flipperzero-firmware-wPlugins#220]
### Describe the bug.

Sub-Ghz - Lock keyboard do not work

### Reproduction

1. Go to Sub-Ghz
2. Go to Read
3. Go to Config
4. Press "Lock Keyboard"

**Comment by RogueMaster** [comment]
Please see if this problem occurs in the 0812 v3 version

**Comment by Foul** [comment]
Still not working in 0.64.1-0812-RMv3
already mentionned on the Subghz/Discord channel yesterday :
"Foul — Hier à 12:49
How to lock keyboard when scanning? Nothing happen when clicking on it.."

**Comment by RogueMaster** [comment]
Checking into why it may not work... Just confirmed all of https://github.com/flipperdevices/flipperzero-firmware/pull/1343 is in there

**Comment by RogueMaster** [comment]
@PolymerPrints it seems this commit https://github.com/RogueMaster/flipperzero-firmware-wPlugins/releases/tag/0.63.5-0806-RM-NOFAP broke the Lock Keyboard. Could you review how to get it working again? Thank you!

**Comment by Maycuz** [comment]
@RogueMaster Sure, I'll have a look

**Comment by RogueMaster** [comment]
Fixed on latest commit by @PolymerPrints , thank you!
