### ISSUE TITLE
Stuck on restarting

### ISSUE THREAD

**Issue by SonnoOcea** [RogueMaster/flipperzero-firmware-wPlugins#228]
Hi,
While updating with a friend to this custom FW (yes, we already updated to latest stock version first and followed the procedure in the README) our freshly arrived Flipper0, it seemed to be stuck/bricked on the "Restarting..." screen.
After 5mins we decided to pull the plug and reboot forcefully, after which it rebooted and started to update and it completed succesfully.
This issue is just for posterity, and to ask the devs if this is intended.

You owe us a clean pair of underpants :)
Have a nice day

**Comment by RogueMaster** [comment]
I think you are describing an issue on qFlipper?
