### ISSUE TITLE
Profiling in SubGHz section

### ISSUE THREAD

**Issue by albertoglezc** [RogueMaster/flipperzero-firmware-wPlugins#229]
### Description of the feature you're suggesting.

It would be nice to have profiles in SubGHz section with a definición file like

Name:frequency,modulation,<raw/noraw>

If some remote controls or systems uses a known frequency it would be mire easy (instead of using first Frequency Analizer) and after that try to use modulation to capture data or try raw..

**Comment by RogueMaster** [comment]
This could be useful on both RM and OFW. Please do PR there too if you decide to work on it

**Comment by RogueMaster** [comment]
Closing for now, hopefully it's implemented on main
