### ISSUE TITLE
Battery view update without reboot

### ISSUE THREAD

**Issue by ol1ves** [RogueMaster/flipperzero-firmware-wPlugins#230]
### Describe the enhancement you're suggesting.

Changing the battery view in desktop settings doesn't change without a reboot. Not sure if this is an intended feature or a bug (or something that requires WAY too much effort to do) but would be nice if you can change the desktop battery view and immediately return and see it on the desktop without needing to reboot fz.

**Comment by RogueMaster** [comment]
Intended to conserve reads to storage since it does it often otherwise. Open to more elegant solutions to update / store running setting.
