### ISSUE TITLE
Return to merged NFC disctionary file

### ISSUE THREAD

**Issue by tkerby** [RogueMaster/flipperzero-firmware-wPlugins#236]
### Describe the enhancement you're suggesting.

See issue logged at https://github.com/UberGuidoZ/Flipper/issues/88

Using the merged file to replace the flipper official one leaves the user dictionary for the user to add keys and not be overwritten on each update. At the moment, I'm having to merge files manually on every firmware update.

**Comment by RogueMaster** [comment]
this was done already...
