### ISSUE TITLE
Confusion about esp8266 integration

### ISSUE THREAD

**Issue by Einstein2150** [RogueMaster/flipperzero-firmware-wPlugins#237]
In the latest changelog the integration of the esp8266 deauther-module is mentioned:
`Added [WiFi (Deauther) (By Timmotools)](https://github.com/Timmotools/flipperzero_esp8266_deautherv2) (Inspired by WiFi (Marauder) (By 0xchocolate) and DSTIKE Deauther (By SequoiaSan)) HIDDEN "INTAPP_esp8266_deauth" due to Req: ESP8266`

Does this feature needs individual build/compiling? I can't see a menu-entry for the deauther in the release-firmware... !?

**Comment by RogueMaster** [comment]
Yes, you need to edit compiled apps and re-compile to include anything hidden per readme.

**Comment by Einstein2150** [comment]
Editing? Where is the right spot for including WiFi deauther? I compiled from source with the basic settings and there is only marauder included ...

`Loaded 98 app definitions.
Firmware modules configuration:
Service:
	 rpc, bt, cli, dialogs, dolphin, desktop, gui, input, loader, notification, power, storage
System:
	 updater_app
App:
	 Clock, subghz, UniRFRemix, lfrfid, nfc, infrared, gpio, wifi_marauder, ibutton, bad_usb, u2f
Plugin:
	 APPS_BarcodeGenerator, APPS_BluetoothRemote, APPS_dec_hex_converter, APPS_DolphinBackup, APPS_DolphinRestorer, INTAPP_HIDAnalyzer, APPS_MouseJacker, APPS_MouseJiggler, APPS_MusicPlayer, APPS_NRFSniff, APPS_Paint, INTAPP_Picopass, APPS_SentrySafe, APPS_SpectrumAnalyzer, APPS_WAVPlayer
Debug:
	 vibro_test, usb_test, usb_mouse, uart_echo, lfrfid_debug, bt_debug
Archive:
	 archive
Settings:
	 bt_settings, notification_settings, storage_settings, power_settings, desktop_settings, passport, system_settings, about
StartupHook:
	 crypto_start, infrared_start, nfc_start, music_player_start, subghz_start, lfrfid_start, ibutton_start, bt_start, power_start, storage_start, updater_start
Package:
	 basic_apps, basic_plugins, basic_services, custom_apps, custom_games, debug_apps, wifi_plugins
Game:
	 GAME_2048, GAME_Arkanoid, GAME_Dice, GAME_FlappyBird, GAME_MontyHall, GAME_Raycast, GAME_Snake, GAME_tamagotchi_p1, GAME_Tetris, GAME_TicTacToe, GAME_VideoPoker
Firmware size
.text         674944 (659.12 K)
.rodata       153688 (150.09 K)
.data           5388 (  5.26 K)
.bss           10548 ( 10.30 K)
.free_flash   214112 (209.09 K)
Setting build/f7-firmware-C as latest built dir (./build/latest/)
	HEX	build/f7-firmware-C/firmware.hex
	BIN	build/f7-firmware-C/firmware.bin
firmware.bin:  204 flash pages (last page 72.66% full)
	DFU	build/f7-firmware-C/firmware.dfu
2022-08-17 07:16:37,590 [INFO] Firmware binaries can be found at:
	dist/f7-C
`
