### ISSUE TITLE
NFC and BT/BLE changes in this repo makes crush if try to emulate Nice FloR-S protocol.

### ISSUE THREAD

**Issue by Eng1n33r** [RogueMaster/flipperzero-firmware-wPlugins#24]
**Describe the bug**
By elimination method I figured out that NFC and BT/BLE part changes leads to hard fault if you try emulate Nice FloR-S protocol

**To Reproduce**
1. Open Nice FloR-S signal
2. Press button 'SEND'
3. Flipper reboots with HARD FAULT message

**Expected behavior**
No conflicts

**Target**
F7

**Comment by RogueMaster** [comment]
Could you try and build https://github.com/RogueMaster/flipperzero-firmware-wPlugins/tree/ab9b667c7db5e7c27cd5dbfc20e06c87eb2c155e and let me know if it fixes it

**Comment by Eng1n33r** [comment]
> Could you try and build https://github.com/RogueMaster/flipperzero-firmware-wPlugins/tree/ab9b667c7db5e7c27cd5dbfc20e06c87eb2c155e and let me know if it fixes it

I think I made same changes like in your patch commit. So it should compile correct.

**Comment by r3df0xx** [comment]
But there is still a problem with nfc changes. Please check, as it leads to hard fault in runtime.

**Comment by Eng1n33r** [comment]
Please check NFC also, as it makes hard fault.

**Comment by RogueMaster** [comment]
Latest update to main builds revert both sets of changes, thank you for your testing

**Comment by RogueMaster** [comment]
#1238 #1242 heads up these fixes made Nice FloR-S stop working per Eng1n33r

**Comment by RogueMaster** [comment]
Hey @Eng1n33r , if either of these pulls get approved, #1238 or #1242, the main dev update will break that Nice FloR-S emulation. Any idea if it is caused by a bug in the changes, or just a change in protocol support? If Nice FloR-S support can be updated to work with the pull changes, you may want to consider if they get approved.
