### ISSUE TITLE
Transmission is blocked at my region

### ISSUE THREAD

**Issue by Mika73** [RogueMaster/flipperzero-firmware-wPlugins#241]
### Describe the bug.

Transmission is blocked at my region. 

### Reproduction

When trying to send Megacode from Misc directory get error that transmission is blocked at my region. 
![0F94F107-50E9-4653-9D47-1823B58F192E](https://user-images.githubusercontent.com/12106091/185049472-96447f68-2793-4df9-8fe2-f95ea09883c5.jpeg)

### Target

Transmission is blocked at your region

**Comment by L0rdS474n** [comment]
Have you updated extended_range.txt and setting_user.txt to support extended ranges?

You find them in subghz/assets on you SD card

**Comment by Mika73** [comment]
I have copy old ones from computer to sd card and replace those files there. Maybe something wrong with files I have. Is there link to working ones so can try replace those?

**Comment by L0rdS474n** [comment]
Can upload my files, just a notice that the extended_range is now named extended_range.txt.

You can find settings here that I just drop in my assets folder after a FW flash

https://ucarecdn.com/a508410b-97fe-4c6a-9ee7-d26df864e4b0/

**Comment by RogueMaster** [comment]
Install latest release, update `extend_range.txt`, try locked file such as TPMS sub @ 300MHz
