### ISSUE TITLE
Flipper crashes when pressing the left button

### ISSUE THREAD

**Issue by sundset** [RogueMaster/flipperzero-firmware-wPlugins#242]
### Describe the bug.

When pressing the left button (start screen) and the clock appears, flipper does a hard crash and reboots. 

### Reproduction

1. Switch Flipper on
2. Press < button to open Clock
3. Flipper crashes and reboots

**Comment by zviratko** [comment]
Can confirm. Opening Clock for the first time worked, it showed the time, refreshed correctly and I was able to quit it cleanly. When opening it again, it crashed instantly. Now it crashes every time.

**Comment by Maycuz** [comment]
Clock is broken in latest release (@RogueMaster is aware).

**Comment by RogueMaster** [comment]
If you can, test with current code

**Comment by pretzelmonies** [comment]
Also can confirm with newest release 0.64.5-0817-RM. Crash occurs from left key press from home screen, or "clock" app from main menu.

**Comment by RogueMaster** [comment]
Fixed on todays release
