### ISSUE TITLE
Since clock now defaults to 12h clock... 

### ISSUE THREAD

**Issue by L0rdS474n** [RogueMaster/flipperzero-firmware-wPlugins#264]
### Describe the enhancement you're suggesting.

Can we make the choice permanent to either 12 or 24h?
Really hate 12h clock and can cope with the fact that I change it to 24h but as it is now I'm stuck with an uggly 12h clock...

**Comment by RogueMaster** [comment]
You should compile your own FW

**Comment by L0rdS474n** [comment]
Yes, but why not have a setting for this?

**Comment by RogueMaster** [comment]
Why not PR the setting you want?
