### ISSUE TITLE
App priority vs games - 2 versions?

### ISSUE THREAD

**Issue by tkerby** [RogueMaster/flipperzero-firmware-wPlugins#265]
### Describe the enhancement you're suggesting.

While apps are needing compiled into the main firmware and decisions are being made what to build, I’ve noticed some useful functionality is being lost like the hid analyser and rfid fuzzing. 

Would you consider doing releases that favour apps over games? Perhaps both could be published

**Comment by RogueMaster** [comment]
The new RFID remake will replace the HID Analyzer and RFID fuzzer is already being developed for the remake.

Once OFW pushes the new RFID, I will update and re-add Fuzzer update when available.
