### ISSUE TITLE
MF Classic dictionary priorities

### ISSUE THREAD

**Issue by zviratko** [RogueMaster/flipperzero-firmware-wPlugins#266]
### Describe the enhancement you're suggesting.

Hi,
I think NFC/Read shuld first use the default dictionary and only then switch to the (larger) user dictionary. It takes about 2 hours to read a MF Classic card "by default" without skipping the user dictionary attack, few seconds with the default dictionary. (I also feel there has been regression in there, it used to be much faster, but it probably depends on what "default" keys the card uses).

Can the order of the dictionaries be switched? Or should I take this upstream?

Thanks

**Comment by RogueMaster** [comment]
Please submit upstream
