### ISSUE TITLE
Dolphin restore overwrites backup data... 

### ISSUE THREAD

**Issue by L0rdS474n** [RogueMaster/flipperzero-firmware-wPlugins#270]
### Describe the bug.

Do a backup with the plugin, update with some RougeMaster FW.
Now do a restore with the restore plugin and you will have something else than when you did the backup. 

### Reproduction

1. Switch on
2. Make a backup with the plugin
3. Do an update to some RougeMaster FW
4. Make a restore with the plugin
5. Note the dolphin stats are most likely different than the backup. 

### Target

Latest RougeMaster FW

### Anything else?

Probably because there is a state file in resources folder for the backup.
Not sure why this needs to be there in the first place.
Should be possible to remove to avoid overwriting when doing an upgrade of the Flipper

**Comment by Maycuz** [comment]
Might be a different problem, but I encountered similar issues when my internal storage was full. Would be good to check the remaining available space.

**Comment by RogueMaster** [comment]
You are right, resources would override the .dolphin.state, I have changed naming on included sample file.
