### ISSUE TITLE
Stealth capture

### ISSUE THREAD

**Issue by Foul** [RogueMaster/flipperzero-firmware-wPlugins#272]
### Description of the feature you're suggesting.

No led
No sound
No rumble when capturing..

With of course on/off possibility

Just an idea 💡

**Comment by RogueMaster** [comment]
This is a good idea to have the device be in a "stealth" mode that always has no LED and no VIBRO and no SOUND... everything made for it would have to listen to it, or it would need to be used by notifications app... feel free to PR if you make it :)

**Comment by RogueMaster** [comment]
Since this isn't an issue but a feature enhancement I wont be working on, I am closing this 😄
