### ISSUE TITLE
U2F

### ISSUE THREAD

**Issue by RogueMaster** [RogueMaster/flipperzero-firmware-wPlugins#275]
### Describe the enhancement you're suggesting.

Who uses U2F? I could disable it for 15+KB and re-add it when faps return...

### Anything else?

I don't use it, I prefer more games...

**Comment by Foul** [comment]
i'm using it, Security keys on Github :D

**Comment by Painkiller8818** [comment]
i also use it for google, fb etc. almost all stuff where i can use it, except microsoft :D

**Comment by Gallocon** [comment]
I use it. Games are fun for experimentation and pushing boundaries, but I've yet to find a game on Flipper worth killing U2F over.

I cannot wait until the FAP loader is working so you don't have to do this song-and-dance with features. I can tell it's been a difficult battle.

**Comment by fobrice** [comment]
Like @Foul  & @Painkiller8818 use it for google, fb, github, private gitlab and linux auth with pam-u2f.

**Comment by t0mab** [comment]
Hi me as well beginning to use it when I received the flipper and I think it's worth keeping !
Same as @Foul , @Painkiller8818, @fobrice mainly for github, private gitlab, and linux pam (sudo without password & more)
