### ISSUE TITLE
Frequency scanner

### ISSUE THREAD

**Issue by GambleMoMoney** [RogueMaster/flipperzero-firmware-wPlugins#281]
### Describe the bug.

When trying to use the frequency scanner it picks up on some things but not others. I'm trying to see what frequency my garage door uses but it isn't pulling anything up, but if I try it with my car keys it works perfectly fine. My garage door should use 315Mhz, I have been able to see it in the past.

### Reproduction

Sub Ghz menu
Frequency analyzer
Use any 315Mhz device

### Anything else?

I read online somewhere that it was a software issue, but I really don't want to have to downgrade.

**Comment by RogueMaster** [comment]
Please check if this is an issue upstream and submit there. This is not something I would be working on.
