### ISSUE TITLE
Will iButton Be back?

### ISSUE THREAD

**Issue by Kikithecat12345** [RogueMaster/flipperzero-firmware-wPlugins#282]
### Description of the feature you're suggesting.

Will iButton be back in the firmware? I would like it to be as I use it to enter my apartment where I live.

**Comment by RogueMaster** [comment]
Yes it will, please don't open issues without even reading the read me

**Comment by trojan-dell** [comment]
I read the whole "read me", I did not find how to return the hidden iButton to the menu, please help. I'm just a beginner
