### ISSUE TITLE
VideoPoker is bugged

### ISSUE THREAD

**Issue by Foul** [RogueMaster/flipperzero-firmware-wPlugins#283]
### Describe the bug.

Pairs 2 through 9 are not recognized

### Reproduction

Just play @ Video Poker, try to get a small pair.. and game see nothing..

2-2
3-3
4-4
5-5
6-6
7-7
8-8
9-9

**Comment by RogueMaster** [comment]
I think this is being worked on by the original dev, since I won't be working on this, closing this issue
