### ISSUE TITLE
add on main firmware the: flipperzero-sentry-safe-plugin

### ISSUE THREAD

**Issue by MrCook1es** [RogueMaster/flipperzero-firmware-wPlugins#288]
### Description of the feature you're suggesting.

Hi, athanks for your great work!
I reguarly update my flipper-zero with your firmware.

It will be great if you implemented the **flipperzero-sentry-safe-plugin** on the RM release .
https://github.com/H4ckd4ddy/flipperzero-sentry-safe-plugin

congratulations again for your work

**Comment by Foul** [comment]
Already included in B side :

Latest Updates:
Apps HIDDEN for compile space can be found on Side B in the update folder.

**Comment by MrCook1es** [comment]
I'm sorry but I can't find "Side B" or the "update folder" :'(

**Comment by RogueMaster** [comment]
Use SD install method for Side A

**Comment by Foul** [comment]
> I'm sorry but I can't find "Side B" or the "update folder" :'(

Download firmware
unzip
go to unziped folder
untar recources.tar (with 7zip or anything else)
go to /resources/update/ folder and BINGO !!! you find the B side :D
Flash as usual..

**Comment by MrCook1es** [comment]
> 

Thanks a lot for the reply!
sorry, I looked in the firmware 0.65.3-0825-RM and there the update folder is empty.
This is a change that you only made in the .Av2
Thanks and great job!
