### ISSUE TITLE
The Passport on realease 0.65.4-0901-RM.Av2 is hard crashing flipper

### ISSUE THREAD

**Issue by chazp246** [RogueMaster/flipperzero-firmware-wPlugins#298]
### Describe the bug.

Flipper will crash if i try to open passport. Both by right button and also in the settings.

### Reproduction

1a. press right button on the unlocked home screen
1b. open passport from within the setings

**Comment by RogueMaster** [comment]
Will review for all levels

**Comment by toxyl** [comment]
On my device the name I gave it was reset on reboot. I was able to set it again using the Name Changer, but any subsequent attempts to use the Name Changer resulted in Hard Faults. Even after reboots the Name Changer kept crashing, but after opening the Passport once, I don't experience any crashes with the Name Changer. Once I update the name, the above starts anew. I'm also using 0.65.4, maybe these two issues are related?

**Comment by RogueMaster** [comment]
Fixed on V2
