### ISSUE TITLE
Sub-Brute plugin - Flipper freeze after run Came brute

### ISSUE THREAD

**Issue by 54m0hT** [RogueMaster/flipperzero-firmware-wPlugins#315]
### Describe the bug.

Flipper freeze after a few seconds when running Came brute, needed force reboot.

If run a short brute with custom packet brute, all run ok. But with a large bruteforce, flipper freeze after send between 80 to 190 packets.

### Reproduction

Run SubBrute Plugin, select CAME 12 bit brute, run and wait a few seconds. Led is blinking but flipper is freeze.

### Target

091022 update from source.

### Anything else?

I tried with more memory free excluiding some apps with same results.

**Comment by RogueMaster** [comment]
Please open issue on unleashed for fix
