### ISSUE TITLE
BT Device Name missing "zzRogue" after 0.66.2-0913-RM.A

### ISSUE THREAD

**Issue by thespawnat** [RogueMaster/flipperzero-firmware-wPlugins#318]
### Describe the bug.

after installing 0.66.2-0913-RM.A, Android App is unable to connect. 

in the BT Devices on Android is the Flipper shown without "zzRogue".

FW 0.66.2-0911-RM.A has still "zzRogue" in the Device Name present

If you disconnect / forget the Device, you can reconnect it fine with the "new" name

### Reproduction

install 0.66.2-0913-RM.A
scan BT Devices -> Flipper without "zzRogue" Naming
restore 0.66.2-0911-RM.A
scan BT Devices -> Flipper with "zzRogue" Naming

### Target

0.66.2-0913-RM.A

**Comment by Antti** [comment]
It's the other way round for me. With zzRogue android app couldn't find my flipper.

**Comment by Foul** [comment]
For me it's better.. i see multiple flipper lol
![BT](https://user-images.githubusercontent.com/829842/189917810-5b5d9d5b-8b2f-4f1d-85e6-a5a2207eb45f.png)

**Comment by RogueMaster** [comment]
this was changed back in last release to behave just like unleashed / stock 'xFlipper'

**Comment by Foul** [comment]
My screen is done with latest firmware..
