### ISSUE TITLE
feature: "Panic" mode

### ISSUE THREAD

**Issue by netleafdev** [RogueMaster/flipperzero-firmware-wPlugins#32]
**Is your feature request related to a problem? Please describe.**
No current problem, just thinking ahead.

**Describe the solution you'd like**
We should have a one-time-use "Hide" or "Panic" mode that sets the Flipper device back to its default TX locked state (and then removes the option to do so), in case the device was obtained by someone (like, your big brother) who wants to see whether it was unlocked or could be used to TX certain frequencies he suspects you of having used.

It could hinge on the presence of a file or a bit within the file that when present removes the UI entry for "Panic" and locks the TX. This way no one can know of the UI option that you used to lock the TX. When you get back home, connect it (or the SD card) to the PC and you flip that bit or remove the file, then that re-adds the UI entry for "Panic" and unlocks the TX again.

**Describe alternatives you've considered**
Granted there is already the ability to lock the entire device. This is in case you are compelled to somehow (depending on how much of a bully your big brother is) or want to be able to easily "prove" to him you did nothing wrong.

**Additional context**
Don't have any context, this is just a nice-to-have.

**Comment by RogueMaster** [comment]
I don't have any siblings so not too worried about it.... dumb mode ideally could help for what you want when it is implemented....
