### ISSUE TITLE
Can not find "Applications" in Menu

### ISSUE THREAD

**Issue by S0ulan** [RogueMaster/flipperzero-firmware-wPlugins#328]
### Describe the bug.

I can not find "Applications" in Menu. I have a folder "apps" with *.fap files on the SD Card. But no menu entry "Applications".

### Reproduction

1. Switch on
2. Find out: no menu entry "Applications"

**Comment by HenryKleinschmidt** [comment]
Try flashing side b firmware. That did the trick for me

**Comment by Foul** [comment]
Because it's not yet implemented in RM ! wait the next update (Only original and Unleashed have it for now..)
