### ISSUE TITLE
Possible Magspoof Module ?

### ISSUE THREAD

**Issue by vivinano** [RogueMaster/flipperzero-firmware-wPlugins#329]
### Describe the enhancement you're suggesting.

I saw there was a magspoof module in an old version of flipper is there a way to convert that for the newer firmware 

https://github.com/dunaevai135/flipperzero-firmware/tree/feature/nomodule/applications/magspoof

if not able to just let me know

**Comment by RogueMaster** [comment]
Don’t have the hardware or time, sorry

**Comment by 0ki** [comment]
Hold up, what do you mean, hardware? It should work with the built in LF RFID antenna.

Can this module be compiled in or are there format changes that need to be made?

**Comment by RogueMaster** [comment]
Changes are needed for sure... this one may be closer... https://github.com/wetox-team/flipperzero-firmware/tree/ezhevita/magspoof, if you compile it and get it to work we can add it in for others to try too

**Comment by RogueMaster** [comment]
Also, if using internal antenna, we need some sort of guarantee or clarification that it wont brick RFID after continuous use, otherwise, external antenna is better
