### ISSUE TITLE
Clock app displays 12-noon as AM

### ISSUE THREAD

**Issue by PercyJax** [RogueMaster/flipperzero-firmware-wPlugins#330]
### Describe the bug.

In 12 H mode, the Flipper displays the current time (i.e. 12:33 pm or 1233 hours) as 12:33 am

### Reproduction

1. Install 0.66.3-0918-RM
2. Open Clock App

![IMG_9997](https://user-images.githubusercontent.com/9935391/190918020-f65ad40b-6e0c-4071-8c1a-79200d8c51de.PNG)
![IMG_9996](https://user-images.githubusercontent.com/9935391/190918021-e1378b3f-145f-46bc-a87e-37e96a52b8aa.PNG)

**Comment by RogueMaster** [comment]
Fixed for next release
