### ISSUE TITLE
NFC 14a SN emulation bug

### ISSUE THREAD

**Issue by gloglas** [RogueMaster/flipperzero-firmware-wPlugins#335]
### Describe the bug.

NFC works as should but after scanning 14a card and emulating UID, emulating no longer works.
If you exit back to NFC menu or home screen and try to emulate one of your saved cards, it doesn't work.
If you try to read a card, it will read as it should.
The NFC emulation just stops working until flipper restarts.

### Reproduction

Try NFC funcionality, emulate something.
Everything works.

Scan this type of card:
```
Tag type: ISO 14443-4
NXP - Mifare DESFire EV1 8k

Technologies Available:
IsoDep, NfcA, NdefFormatable

Serial number 04:5B:2A:C1:19:5B:04 # random serial num
ATQA 0x0344
SAK 0x20
ATS 0x80
```
Go to More > Emulate UID *\*press OK\**
Emulation starts, yet nothing cannot be read with a reader (meaning another device).
Exit NFC app
Go back in NFC app and try to emulate anything.
It will not emulate, until you reboot os.

### Target

0.66.3-0921-RM

**Comment by RogueMaster** [comment]
Please test with OFW and open Issue in OFW for fix.
