### ISSUE TITLE
NFC EMV interpretation app

### ISSUE THREAD

**Issue by 0ki** [RogueMaster/flipperzero-firmware-wPlugins#338]
### Describe the enhancement you're suggesting.

Is there a reason why the EMV app is not available under NFC->extra actions anymore?

 I know it's experimental and will (probably forever) be limited in functionality but it was still useful.

**Comment by RogueMaster** [comment]
EMV is not supported anymore I think, regardless, ask in main and see what they say...

**Comment by 0ki** [comment]
Apparently there's a bug where the app doesn't appear in the menu but the code is there!
https://github.com/flipperdevices/flipperzero-firmware/issues/1527
