### ISSUE TITLE
NFC Emulation not working

### ISSUE THREAD

**Issue by Phreak87** [RogueMaster/flipperzero-firmware-wPlugins#345]
Hey,

tried to emulate a saved MFC 1k-Card with NFC app but reading with Android doesn't work - the same emulation with a PM6 Reader on PC works. 

But ... Its not a placement issue of the flipper because "detect Reader" will be recognized all the time.

### Reproduction

Clone Card using NFC-Read and save (all sectors read)
run "More" 
run "emulation" 

### Target

MFC-1K

**Comment by RogueMaster** [comment]
See if you have the problem in main and open a ticket with main please
