### ISSUE TITLE
Writing on (empty) tag mifare classic | Cloning mifare classic

### ISSUE THREAD

**Issue by superswiegie** [RogueMaster/flipperzero-firmware-wPlugins#352]
### Describe the enhancement you're suggesting.

Currently it's possible to emulate/read (most) Mifare classic tags. I would really like to see the option to write/clone such a tag. 

### Anything else?

Thanks for all the hard work in this fork (L)

**Comment by RogueMaster** [comment]
Thank you, I cannot test this so please make this request on main FW if you find the same problems there...

**Comment by superswiegie** [comment]
Is this option already on the roadmap sinds the latest update?
