### ISSUE TITLE
Provide .tgz firmware package

### ISSUE THREAD

**Issue by augustozanellato** [RogueMaster/flipperzero-firmware-wPlugins#353]
### Description of the feature you're suggesting.

Providing a .tgz firmware package (similar to the one Unleashed provides) would make it possible to flash/update RM firmware using mobile app

**Comment by RogueMaster** [comment]
Sure, what command set is needed for the folder structure and compression for it to work?

**Comment by augustozanellato** [comment]
> Sure, what command set is needed for the folder structure and compression for it to work?

Check here https://github.com/flipperdevices/flipperzero-firmware/blob/0f9ea925d30f7a6183abe1002d680e3d1613a159/.github/workflows/build.yml#L84, should be pretty easy.

**Comment by RogueMaster** [comment]
Sorry, that command doesn't yield the needed result... after running:

root@debian:~/fap/flipperzero-firmware-wPlugins# ./fbt updater_package

What is needed?

**Comment by augustozanellato** [comment]
I tried on my machine and running `tar czpf 420.tgz -C dist/f7-C f7-update-RM420FAP` after `./fbt updater_package` creates a file named `420.gz` in the repo root that can be successfully flashed to flipper using the mobile app

**Comment by RogueMaster** [comment]
Ok, will try on this release

**Comment by RogueMaster** [comment]
Have you tried installing the resulting file? Doesn't seem to work on qFlipper, does it work on mobile?
