### ISSUE TITLE
Favorite Apps not working

### ISSUE THREAD

**Issue by Nordikk** [RogueMaster/flipperzero-firmware-wPlugins#354]
### Describe the bug.

I'm trying to set U2F as a favorite app, but it doesn't work.
I've tried to set it as primary and secondary favorite app, but it still just opens clock, respectively subghz

Am I'm doing something wrong?

### Reproduction

1. Set Favorite App
2. Try to launch favorite App via Shortcut from Desktop
3. ...
4. no profit :/

**Comment by stepjanssen** [comment]
Hi, I noticed this was closed, but I didn't see it fixed in the latest release and I'm having the same issue. Will this be fixed in a release in the near future by any chance?

**Comment by RogueMaster** [comment]
Hold Up or Hold Down for the favorite apps, this was not actually an issue

**Comment by stepjanssen** [comment]
Ok, thanks, this made me realize the issue is only with the remote and I've found a work-around!

**Comment by Gadgetroch** [comment]
Hi,

Hold down works for me, but hold up not.
And i noticed in settings it's inverted.
When i click on primary app i choose secondary and when i click on secondary i choose primary app

**Comment by Gadgetroch** [comment]
Same issue with the last build
