### ISSUE TITLE
0.70.2-1104-RM1839 firmware install failed

### ISSUE THREAD

**Issue by 4DA** [RogueMaster/flipperzero-firmware-wPlugins#406]
### Describe the bug.

I am trying to install 0.70.2-1104-RM1839 firmware on top of vanilla flipper 0.70.1 and at the end see "Update failed" message, "Error 13-0"

![image](https://user-images.githubusercontent.com/364499/200135292-dc32e574-91a3-4c55-8396-0bf3ceb12cae.png)
After this failed update I can see updated desktop but no application is able to start, showing errors.

### Reproduction

1. Vanilla flipper firmware 0.70.1
2. Extract tgz file to flipper sd card (includuing sub resources catalogue)
3. From flipper browser run updater app

**Comment by RogueMaster** [comment]
try again?

**Comment by RogueMaster** [comment]
I don't get this error

**Comment by 4DA** [comment]
okay, my isssue what that I uncompressed resources.tar and deleted the archive (bc read in some other fw to do it) :D

**Comment by RogueMaster** [comment]
yeah, that's wrong, for all firmwares...
