### ISSUE TITLE
Keyboard layout is wrong

### ISSUE THREAD

**Issue by XuliGan4eg2006** [RogueMaster/flipperzero-firmware-wPlugins#407]
### Describe the bug.

Hello! On this custom FW I have issue with bad usb (at the same time in official FW it has fix). Bad usb starts typing commands and ignores keyboard language. (I have changed layout but no result)

### Reproduction

1. Switch keyboard layout on your pc to any except En
2. Start any Bad usb script

### Anything else?

https://imgur.com/a/aiCrPEU - video demonstration
My config: 
![изображение](https://user-images.githubusercontent.com/62839426/200180100-041b5c13-7693-488f-b906-ea453bf3828f.png)
![изображение](https://user-images.githubusercontent.com/62839426/200180107-a45f8cf6-97b4-49bc-a5f9-348e8f7b0699.png)
(newest FW)

**Comment by ESurge** [comment]
Tested changing keyboard layout to Portuguese (`pt-PT`) with `pt-PT` in BadUSB, and keyboard layout to French (`fr-FR`) with `fr-FR` in BadUSB. These work fine.

I think the issue is that there doesn't seem to be a Russian (`ru-RU`) layout for BadUSB.

**Comment by ESurge** [comment]
A workaround for this is to use AltString in the BadUSB script.
