### ISSUE TITLE
Calculator outputs result for div by 0

### ISSUE THREAD

**Issue by FalcoGer** [RogueMaster/flipperzero-firmware-wPlugins#412]
### Describe the bug.

When running the calculator with the input `1/0`, it produces the output `'.214748364`

### Reproduction

1. Open calculator
2. Enter `1/0`
3. Calculate
4. Observe odd behavior

### Target

Flipper Zero

**Comment by RogueMaster** [comment]
Didn't make the calculator, this is the wrong place for this.
