### ISSUE TITLE
USB Midi unable to load, Forced reset of flipper causes crash

### ISSUE THREAD

**Issue by Lrennard** [RogueMaster/flipperzero-firmware-wPlugins#417]
### Describe the bug.

upon launching the USB Midi while attached to a windows 10 laptop the application became stuck loading. tried a forced reset and this caused the device to crash.

was able to restore Flipper0 to 0.71.1 using qFlipper Repair.

Edit: I am aware that my use case for USB-Midi was incorrect, still feel the crash was worth reporting as it required a firmware repair/reflash

### Reproduction

1. attach via usb to windows 10 machine
2. load USB Midi
3. Hard reset Flipper
4.

### Target

USB-Midi

### Anything else?

Have Logs but only from post crash so they same to only document repair

**Comment by RogueMaster** [comment]
Standard reset is enough. No need for firmware reflash. Seems like USB MIDI doesn't work for anything.
