### ISSUE TITLE
Support AiphoneGT Door System Admin Code Brute Force

### ISSUE THREAD

**Issue by Antiklesys** [RogueMaster/flipperzero-firmware-wPlugins#418]
### Description of the feature you're suggesting.

Support for sending NFC Payload for AiphoneGT Door Systems to gain admin access.
This would be a 5 digit string starting with * for Admin and # for Manager codes.
The rest of the digits are numbers.
Official Aiphone documentation states default Admin Code is : *1111 and default Manager code is #2222
If these credentials have been changed from the default ones it still possible to loop 10.000 codes starting from *0000 to *9999 in a very fast manner.
More info on this attack: https://techcrunch.com/2022/11/10/aiphone-door-entry-nfc-bug/
Official documentation:  https://www.aiphone.net/support/software-documents/download/gt/manual/en/GT_setting_manual_Android.pdf

**Comment by RogueMaster** [comment]
Please PR if you want this supported. I think you want to make something like the RFID fuzzer for NFC.
