### ISSUE TITLE
RM11190225-0.71.2-73cde22 make flipper freeze and won't respond

### ISSUE THREAD

**Issue by johnjohnsp1** [RogueMaster/flipperzero-firmware-wPlugins#425]
### Describe the bug.

once updated the firmware with success message after a few secs the device will freeze, background stand still and ignore the pressure of any keys.
you can still reboot the device but once rebooted, with or without SD opted in will freeze again (id say 3 sec no more until freeze), LCD is also always on won't turn off
the only way actually is revert with DFU mode.
i can confirm the RM11180032-0.71.2-f0b9e89 is working good.

### Reproduction

1. update FW RM11190225-0.71.2-73cde22 (latest on folder)
2. once rebooted device will freeze, no action required just wait 3 sec

**Comment by RogueMaster** [comment]
try now
