### ISSUE TITLE
Loading on phone RM

### ISSUE THREAD

**Issue by Yourit7870** [RogueMaster/flipperzero-firmware-wPlugins#426]
### Describe the bug.

Loading rouge master on the app isn’t properly going through. Trying to send it through the computer is not working as well maybe a loading error. “Update failed Error number# (1-60)”

### Reproduction

Update 0.71.1 
Tried to up load the zip. And the tgr. File 
Almost Immediately error #1-60 
Not sure after how to fix 

Tried to reboot and re try.

**Comment by RogueMaster** [comment]
Should be fixed now
