### ISSUE TITLE
Feature request disable custom animations

### ISSUE THREAD

**Issue by Darkcast** [RogueMaster/flipperzero-firmware-wPlugins#438]
### Description of the feature you're suggesting.

ive have noticed that some of the custom disable custom animations are not well optimized and some time it freezes my flipper. it would be nice if there were a way to disable custom animations and just leave stock one. 
thanks

**Comment by RogueMaster** [comment]
You can do this by changing the dolphin folder on the SD card

**Comment by Schecher1** [comment]
> You can do this by changing the dolphin folder on the SD card

Do you happen to have the stock folder with the standard images/animations for the dolphin ?

**Comment by RogueMaster** [comment]
See stock firmware

**Comment by Darkcast** [comment]
why should I change to stock if the issues are the badly made animations

**Comment by RogueMaster** [comment]
Exactly why you can go back to stock firmware, I don't need you using RM version.

**Comment by RogueMaster** [comment]
Just stay on stock, don't switch back

**Comment by Schecher1** [comment]
why are u so mad? I just wanted the normal dolphin back and not this goku or whatever his name is

**Comment by RogueMaster** [comment]
> why are u so mad? I just wanted the normal dolphin back and not this goku or whatever his name is

You didn't give the stupid response, the other guy did. To solve your problem:
- Install official firmware (as previously mentioned)
- Copy dolphin folder from SD card to computer
- Install RM firmware again
- Copy back/Replace the dolphin folder from computer to SD card

**Comment by Schecher1** [comment]
I already did 12 days ago...

**Comment by RogueMaster** [comment]
Ok good, the response was meant for the moron that doesn't see help when he gets it

**Comment by Schecher1** [comment]
Ah now I saw his answer as well, I thought you meant me
