### ISSUE TITLE
Vigik NFC & Pass and Liftmaster parking pass in France

### ISSUE THREAD

**Issue by mikadev** [RogueMaster/flipperzero-firmware-wPlugins#457]
### Describe the enhancement you're suggesting.

In France Vigik nfc or parking pass and Liftmaster parking pass are not working with flipper there is a way to fix or add this feature ?

**Comment by RogueMaster** [comment]
this isn't the right place for this request

**Comment by molotovah** [comment]
Where is the appropriate place because I would be interested too

**Comment by RogueMaster** [comment]
You can ask on the main flipper github for extended functionality of features. They get paid to build out new features
