### ISSUE TITLE
SubGhz issue with specific remote

### ISSUE THREAD

**Issue by kritonpc** [RogueMaster/flipperzero-firmware-wPlugins#458]
Although I've never had any issues with sub ghz and I have RogueMaster FW with the correct config, I encountered an issue today.
I recorded a remote that works at 433.92 and when i pressed send directly after recording it and it was recognized, it showed me a transmission error saying that the specific frequency is not supported (although it is 433.92). I saved it and tried sending it this wat and when selecting the file it shows the error "Cannot parse file". I tried it several times but it doesn't work. When saving it RAW of course it worked, but the rest seems odd. Any idea what can be wrong? Here is the .sub file as it was saved on flipper:

```
Filetype: Flipper SubGhz Key File
Version: 1
Frequency: 433920000
Preset: FuriHalSubGhzPresetOok650Async
Protocol: CAME
Bit: 32
Key: 00 00 00 00 66 CF 63 02
```

**Comment by RogueMaster** [comment]
Please test if this same problem happens on OFW

**Comment by kritonpc** [comment]
I don't have a flipper with OFW. Can you test if the parse error happens in another flipper too?

**Comment by RogueMaster** [comment]
If you don't care to try then don't post here

**Comment by kritonpc** [comment]
It's not the easiest thing to switch firmwares without losing anything

**Comment by RogueMaster** [comment]
I don't know what device you are using, but on the Flipper Zero, it is the easiest to switch and not lose anything

**Comment by kritonpc** [comment]
I recently encountered the same issue with another remote. I get the same errors. I tried it on both RogueMaster FW and OFW and it has the same behavior. The new remote is:
```
Filetype: Flipper SubGhz Key File
Version: 1
Frequency: 433889000
Preset: FuriHalSubGhzPresetOok650Async
Protocol: CAME
Bit: 32
Key: 00 00 00 00 F7 46 88 12

```

**Comment by RogueMaster** [comment]
If you have an issue also happening with OFW please open an issue there.

**Comment by kritonpc** [comment]
@RogueMaster Thanks for the reply. I opened it there too so... Let's see.
