### ISSUE TITLE
Infrared Slow Launch

### ISSUE THREAD

**Issue by m5performance** [RogueMaster/flipperzero-firmware-wPlugins#460]
### Describe the enhancement you're suggesting.

I have noticed since Infrared has been built as a FAP and moved from being internal app to external app the launch became very slow. Suggestion to move it back as internal app to improve launch speed.

**Comment by RogueMaster** [comment]
This is a known issue I can't fix for unless I make it internal again; not trying that for now

**Comment by m5performance** [comment]
Noted, Thank you for your continuous support to keep this repo updated :) Would you be kind enough to guide me on moving it to internal or if there is any documentation that I could refer to?

**Comment by RogueMaster** [comment]
undo https://github.com/RogueMaster/flipperzero-firmware-wPlugins/pull/398 and parts of https://github.com/RogueMaster/flipperzero-firmware-wPlugins/pull/405

**Comment by m5performance** [comment]
Thank you so much
