### ISSUE TITLE
Cannot parse file

### ISSUE THREAD

**Issue by aberg94** [RogueMaster/flipperzero-firmware-wPlugins#463]
### Describe the bug.

Verified file was accurate according to code listed here, I have also removed it from my SD and reapplied it. Its the only file I have this issue with. File is currently in the default path of /any/subghz/Misc/Crosswalk_Unknown.sub

I am running the latest RM firmware 0.72.1, installed after upgrading dev firmware 0.72.1.

### Reproduction

1. Turn on Flipper
2. Head to SubGhz folder
3. Attempt to run Crosswalk_Unknown.sub
4. Cannot parse file

### Target

/any/subghz/Misc/Crosswalk_Unknown.sub

**Comment by ClaraCrazy** [comment]
`Bits: 29` is the issue. Should be 24. Works then

**Comment by RogueMaster** [comment]
Thank you! @ClaraCrazy
