### ISSUE TITLE
Snake Game Score starts at 7

### ISSUE THREAD

**Issue by Frawg1** [RogueMaster/flipperzero-firmware-wPlugins#465]
### Describe the bug.

In snake game the score starts at 7 

but when you die it shows the normal score in score pop up 

### Reproduction

start snake game

**Comment by ClaraCrazy** [comment]
No C dev, so cant fix but:
<https://github.com/RogueMaster/flipperzero-firmware-wPlugins/blob/420/applications/plugins/snake_game/snake_game.c#L129> seems to be the issue. snake-state starts at 7 (length of snake) and nobody ever removed that 7 from the init score

**Comment by RogueMaster** [comment]
This is fixed :) thank you!
