### ISSUE TITLE
Why exactly 23°C for Cool_lo

### ISSUE THREAD

**Issue by airs0urce** [RogueMaster/flipperzero-firmware-wPlugins#467]
Hello. I would like to add air conditioners to universal remotes and I read this document:

https://github.com/RogueMaster/flipperzero-firmware-wPlugins/blob/420/documentation/UniversalRemotes.md

To get better understanding I wanted to ask why 23°C selected as value for Cool_lo? Why not 25 or 26. I don’t mean something wrong, just wanted to understand the meaning of this choice.

**Comment by RogueMaster** [comment]
Please use discord for random questions. The initial release was pulled with this value.

**Comment by airs0urce** [comment]
@RogueMaster Sure, thank you for letting me know about the Discord channel
