### ISSUE TITLE
The Flipper get stuck at the "UPDATING Updating resources" Screen

### ISSUE THREAD

**Issue by Martin-Hausleitner** [RogueMaster/flipperzero-firmware-wPlugins#474]
### Describe the bug.

When i want to install the RM1220-0057-0.73.2-971ef79 its get stuck at the "UPDATING Updating resources" Screen

I tried multiple things:

- flashing on top the unleashed software
- install the 0.73.1 without an SD and then i installed RM1220-0057-0.73.2-971ef79 with an SD
- the unpleased firmware alone is working perfectly

### Reproduction

1. Flashed the 0.73.1 update over qFlipper with an emty sd card
2. then copy the newest RogueMaster update RM1220-0057-0.73.2-971ef79 to the flipper sd
3. I installed the firmware with the update.fuf on the Flipper
4. Now its stuck the the "UPDATING Updating resources" Screen
5. I left the flipper 1h alone but still the progress bar not moves

**Comment by RogueMaster** [comment]
Works for me, I think the problem at hand may be related to reading from SD media. Try renaming and adding another copy and installing that one to see if it works. If you get a more compatible or alternative SD card, it will likely work without an issue.
