### ISSUE TITLE
No XP from games

### ISSUE THREAD

**Issue by FoxLy1312** [RogueMaster/flipperzero-firmware-wPlugins#492]
### Describe the bug.

Since newst Update i cant get XP from Gaming Flappy Bird’s with both devices.

passport freezing several Times.

 anyway, thanks for the great work 🤪

### Reproduction

1 open passport 
2 check score
3 play games 
4 check score 
5 ?
6 Reboot 

### Target

Games

**Comment by RogueMaster** [comment]
This is two issues... the passport issue is being looked into... as for flappy, you get experience every 5 columns...
