### ISSUE TITLE
 How to verify NRF24 is correctly connected?

### ISSUE THREAD

**Issue by exander77** [RogueMaster/flipperzero-firmware-wPlugins#494]
### Description of the feature you're suggesting.

Apps seem to load fine and do something even if I do not connect anything. So I don't really know if it is working or not.

**Comment by jilleb** [comment]
Try a vulnerable mouse + dongle close to it, and sniff to see if you can find anything. Note: you will not find much when the mouse isn't used.

**Comment by exander77** [comment]
> Try a vulnerable mouse + dongle close to it, and sniff to see if you can find anything. Note: you will not find much when the mouse isn't used.

I can try that, but it would be great if the app knew that the NRF24 is really connected.

**Comment by RogueMaster** [comment]
If it changes to Sniffing=Yes, it is connected and working

**Comment by exander77** [comment]
> If it changes to Sniffing=Yes, it is connected and working

Sadly no. If that was the case I would not be complaining. Without anything connected, sniffing can be changed to Yes.

**Comment by RogueMaster** [comment]
I see, that used to not be the case but you are right in that it changes now. @mothball187 any availability to update the NRF Sniffer?

**Comment by exander77** [comment]
> I see, that used to not be the case but you are right in that it changes now. @mothball187 any availability to update the NRF Sniffer?

If that should work than this is actually bug report and not feature request.

**Comment by mothball187** [comment]
@exander77 @RogueMaster if you see possible addresses being displayed in the app when it is sniffing, then that means the radio is connected properly. You should see possible addresses in most environments, as the radio is sniffing data in the 2.4GHz range which is extremely popular. Bluetooth, Wifi, zigbee, etc. all operate in that range.
