### ISSUE TITLE
Infrared is not launching when set as favorite app

### ISSUE THREAD

**Issue by m5performance** [RogueMaster/flipperzero-firmware-wPlugins#495]
### Describe the bug.

When you set the infrared as favorite either primary or secondary you are are unable to launch it and when either holding down or up from the main screen (Animation screen) nothing will happen and Infrared can't be launched from there.  

### Reproduction

1- Set Infrared as favorite. (Either primary or secondary)
2- Go back the main screen (Animation Screen)
3- Hold up or down arrow (depends on what did you set it at)

**Comment by RogueMaster** [comment]
Hi, please use from Applications => Main and it will work
