### ISSUE TITLE
Bluetooth BadUSB

### ISSUE THREAD

**Issue by yodaluca23** [RogueMaster/flipperzero-firmware-wPlugins#497]
### Describe the enhancement you're suggesting.

Let us run normal BadUSB scripts, over Bluetooth, it should definitely be possible, since we already have BadUSB and a Bluetooth controller keyboard. It just needs to be combined! BadBluetooth?

### Anything else?

Related Issue: https://github.com/flipperdevices/flipperzero-firmware/issues/2294

**Comment by RogueMaster** [comment]
Cool, yeah I'm interested... see what you can find and PR if you get it figured out :)

I can't dedicate time to this right now, I just got sick and have a few other projects on my hands...

**Comment by RogueMaster** [comment]
Keep in mind you can't force your flipper to pair to a PC so the hacking part of the badusb is kind of removed...

**Comment by RogueMaster** [comment]
I'm closing this for now since I don't know how to work past the unpaired BT badusb running. Please do feel free to open a PR if you find a solution.
