### ISSUE TITLE
TRex-Runner should be in Games / Update TRex-Runner to the newest version

### ISSUE THREAD

**Issue by maede97** [RogueMaster/flipperzero-firmware-wPlugins#498]
Currently the TRex-Runner Game is to be found under "Misc". However, it should be under "Games".
https://github.com/RogueMaster/flipperzero-firmware-wPlugins/blob/8c898272bb137da3d2e8ed63274cc7ddf39d34b2/applications/plugins/trex_runner/application.fam#L9

**Comment by maede97** [comment]
The newest update of the application is under "Games":
https://github.com/gelin/t-rex-runner

**Comment by RogueMaster** [comment]
Did you compare the code? They are already the same version. It only works as an animation right now since it doesn't jump or have obstacles. Therefore, it remains in Misc till it is playable.
