### ISSUE TITLE
Unable to exit an application

### ISSUE THREAD

**Issue by auino** [RogueMaster/flipperzero-firmware-wPlugins#503]
### Describe the bug.

On `RM0111-2341-0.75.1-a3d7f16`, when opening an application (e.g. RFID fuzzer), it seems not possible to close it.
This was possible on the original firmware, by long pressing the back button.

### Reproduction

1. Open the RFID fuzzer app
2. Long press the back button

### Target

RM0111-2341-0.75.1-a3d7f16

**Comment by RogueMaster** [comment]
Different apps have different options programmed by the creators, this one may not have it... will check into adding

**Comment by RogueMaster** [comment]
Press back twice to exit, it works
