### ISSUE TITLE
Cart key wav fix

### ISSUE THREAD

**Issue by ZabuzaDemon** [RogueMaster/flipperzero-firmware-wPlugins#522]
### Describe the enhancement you're suggesting.

When I used the wave files CartKeyLock78.wav and CartKeyUnlock78.wav they would just back me out to the music app select screen. I download the wave files and compressed them and used audacity to get the bit rate good. Files down below are working but have not been tested on carts to see if these wave files function as they should. Please feel free to test and add this to a patch update.
[CARTKEYFIX.zip](https://github.com/RogueMaster/flipperzero-firmware-wPlugins/files/10674047/CARTKEYFIX.zip)

**Comment by RogueMaster** [comment]
Thank you! Updated
