### ISSUE TITLE
Sub-ghz Outside range allowed...

### ISSUE THREAD

**Issue by Gadgetroch** [RogueMaster/flipperzero-firmware-wPlugins#526]
### Describe the bug.

I receive 300 mhz sub-ghz, and i can send it, which is not allowed
I have no country code in "about" menu, i just get "--"

It's dangerous and need to be locked by country

### Reproduction

1. Get not allowed mhz signal
2. Send it

**Comment by RogueMaster** [comment]
Please open the extend range app and send a screenshot of the settings

**Comment by Gadgetroch** [comment]
Hi,

All is false...

Le jeu. 9 févr. 2023, 19:51, RogueMaster ***@***.***> a
écrit :

**Comment by Gadgetroch** [comment]
HW Version Info :
12.F7B9C6 R01:-- Amipode

Risky Range : No
Ignore Region : No

**Comment by RogueMaster** [comment]
What region are you in?

**Comment by Gadgetroch** [comment]
France

**Comment by maede97** [comment]
Can reproduce (both settings at "no", with region being -- as well, should be EU).
https://docs.flipperzero.one/sub-ghz/frequencies shows that it should actually show a screen that this frequency is not allowed.
Unleashed Fork has this in the docs: https://github.com/DarkFlippers/unleashed-firmware/blob/dev/documentation/DangerousSettings.md

**Comment by RogueMaster** [comment]
Could one of you please try these to see if it fixes the issue?

Web Installer: https://lab.flipper.net/?url=https%3A%2F%2Frogue-master.net%2F%3Ffile%3DRM0211-0.76.1-RegionFix.tgz&channel=RM0211-0.76.1-RegionFix&version=0.76.1

TGZ: https://rogue-master.net/?file=RM0211-0.76.1-RegionFix.tgz

**Comment by Gadgetroch** [comment]
I m in holidays... I can test it Monday

Le sam. 11 févr. 2023, 18:54, RogueMaster ***@***.***> a
écrit :

**Comment by RogueMaster** [comment]
I was able to test with some TPMS files... prior to the fix, on OFW, and after this fix. I think this is fixed. Please let me know if you have a different experience.
