### ISSUE TITLE
Touchtunes

### ISSUE THREAD

**Issue by ZabuzaDemon** [RogueMaster/flipperzero-firmware-wPlugins#528]
### Describe the bug.

When you select touchtunes_brute_map it can not find the files due to them not being on the flipper.

I don't know if this is intentional? If it is then we just download it and add the touchtune file to subghz folder. This seems to gotten me a bit closer to it working since now the remote finds files to use.
[TouchTunes_files.zip](https://github.com/RogueMaster/flipperzero-firmware-wPlugins/files/10706028/TouchTunes_files.zip)
File is here if you want to add it to the subghz folder.

### Reproduction

1. go to Sub-GHz Remote
2. select touchtunes_brute_map and this will show the issue

### Anything else?

I will be doing more digging around for things that dont work or have issues using and hopefully help you all out.

 New to this stuff so bare with me, I'm willing to learn and help out when I can even if its little things like this.

**Comment by ESurge** [comment]
Sub-GHz Remote app and/or Sub-GHz Playlist app read text files that map to Sub-GHz captured files in .sub file format.

If you don't have the files needed, you can check [UberGuidoZ's Flipper Repo](https://github.com/UberGuidoZ/Flipper )
