### ISSUE TITLE
After update 303.875 MHz shows as Transmission is blocked

### ISSUE THREAD

**Issue by vaidasnet** [RogueMaster/flipperzero-firmware-wPlugins#529]
### Describe the bug.

After update to RM0211-1305-0.76.1-6d6e96f
303.875 MHz which used for customer assistance buttons (Lowes, Walgreens) doesn't work anymore, shows: Transmission Blocked
It worked in previous version, I didn't make any changes to **setting_user.txt** or **extend_range.txt**

### Reproduction

1. open Sub-GHz
2. open Saved
3. Choose "Customer assistance buttons"
4. go to "Lowes" or "Walgreens"
5. run any .sub here

**Comment by vaidasnet** [comment]
NOTE: with unleashed firmware 303.875 MHz works fine

**Comment by RogueMaster** [comment]
Use the Extend Range app to ignore the default region restrictions to allow this frequency
