### ISSUE TITLE
updater_package unable to compile

### ISSUE THREAD

**Issue by alvarotorijano** [RogueMaster/flipperzero-firmware-wPlugins#530]
### Describe the bug.

This repo is not able to compile with the updater_package option. The oficial firmware does so it seems to be a problem with any change made in this repo. Or I can be missing something of course.
The error reported goes as follows: 

applications\settings\passport_app\dolphin/helpers/dolphin_deed.h:80:9: error: c
onflicting types for 'dolphin_deed_get_weight'
   80 | uint8_t dolphin_deed_get_weight(DolphinDeed deed);
      |         ^~~~~~~~~~~~~~~~~~~~~~~
In file included from applications\services/dolphin/dolphin.h:3,
                 from applications\settings\passport_app\passport.h:11,
                 from applications\settings\passport_app\passport.c:1:
applications\services/dolphin/helpers/dolphin_deed.h:80:9: note: previous declar
ation of 'dolphin_deed_get_weight' was here
   80 | uint8_t dolphin_deed_get_weight(DolphinDeed deed);
      |         ^~~~~~~~~~~~~~~~~~~~~~~
        CC      applications\plugins\nrfsniff\nrfsniff.c

### Reproduction

git pull --recurse / git clone --recurse this repo
./fbt.cmd (from windows) updater_package

### Target

updater_package

**Comment by RogueMaster** [comment]
I can compile with no issues. Are you compiling on a fresh clone?

**Comment by alvarotorijano** [comment]
I am with no success.

**Comment by maede97** [comment]
Had the same issue. Fully DELETING the folder and cloning again (then building again) resolved the issue for me. Only deleting build and dist did not help!

**Comment by alvarotorijano** [comment]
Please reopen this case. It is not possible to compile on windows using a fresh clone and running the line above
