### ISSUE TITLE
Unleashed sub ghz works sometimes

### ISSUE THREAD

**Issue by Hammes50** [RogueMaster/flipperzero-firmware-wPlugins#536]
I've installed new version of unleashed, using sub ghz to  record and then send for key fob it works, but when saved and try to use again with saved version when it sends it won't work, only works for initial first record and send before saved. What am I doing wrong or what should I do to fix? Please help still new to flipper, thank you.

**Comment by RogueMaster** [comment]
This is not unleashed, please open there...
