### ISSUE TITLE
NFC sector keys missing

### ISSUE THREAD

**Issue by drake4m** [RogueMaster/flipperzero-firmware-wPlugins#537]
### Describe the bug.

Hello,

The 2 latest builds have issues with the NFC emulating. I read several mifare classic 1k cloned cards and fobs, succeed to find all keys and read all sectors but when emulating keys are missing randomly in sectors and some are tagged as completely bad or missing. I COMPARED THE dumps with MCT. OFW and Unleashed don't have that issue on latest builds. 

### Reproduction

Read any mifare classic 1k
Emulate it (missing keys and sectors randomly)
Reader does not recognize the emulated card

### Target

NFC

**Comment by RogueMaster** [comment]
RM has added NFC V, MRTD AND SLIX.... with that said... our Mifare Classic 1k code is the same as Unleashed... it is very odd it is not working... checking into this... will see if I can make a NFC fap to save some features to side load and revert to original code...

**Comment by Wisiewig** [comment]
the reason for this is because of the reader and the copper coil on in the card, The flipper just isnt powerful enough to account for the differences in the frequencies, nor is it powerful enough to auto pwn a mifare classic 1k card
