### ISSUE TITLE
Web Installer issue

### ISSUE THREAD

**Issue by Xbxjdjdjd** [RogueMaster/flipperzero-firmware-wPlugins#539]
### Describe the bug.

When trying to use web install, error "Failed to fetch firmware: TypeError: Cannot read properties of undefined (reading 'buffer')" appears (view attached photo)
<img width="419" alt="Screenshot 2023-03-01 at 6 47 59 PM" src="https://user-images.githubusercontent.com/126214000/222318163-e48dc28a-b86a-4318-a203-d8106c975aff.png">

### Reproduction

1. Go to web installer
2. Click install after connecting flipper via usb cable
3. error wil pop up

**Comment by RogueMaster** [comment]
This is not an issue with the latest release. What file name are you trying to install?

**Comment by JonathanERC** [comment]
Hello @Xbxjdjdjd I had the exact same issue, just download the ".tgz" package from the repository or Patreon page and then click "Install from File" in the Web Installer. It should install the update successfully. Hope it helps.

Thanks RogueMaster and Contributors for the new release.

**Comment by RogueMaster** [comment]
If you can't post the FULL name of the file you are trying to install, please don't post. This is why this post was closed

**Comment by JonathanERC** [comment]
> 

Hello, I just tried using latest GitHub release "RM0228-1236-0.78.2-5eb5e99" and Web installer in Google Chrome Version "110.0.5481.178 (Official Build) (64-bit)" with no extension and no cache, the same situation remains:
![image](https://user-images.githubusercontent.com/19720181/222469719-25f15442-ac7e-42e3-9eb2-15ad305523e7.png)
![image](https://user-images.githubusercontent.com/19720181/222470121-301a06b8-accb-4c16-92fd-3c5e8c990d84.png)

**Comment by RogueMaster** [comment]
Thank you for providing the file name, please try again now.

**Comment by JonathanERC** [comment]
It worked like a charm now with "RM0228-1236-0.78.2-5eb5e99". Thank you so much.
![image](https://user-images.githubusercontent.com/19720181/222476290-dfe0e772-4132-446c-bc07-7ebb83998103.png)
![image](https://user-images.githubusercontent.com/19720181/222476351-79430c35-1f04-469c-866e-fe5d946c64ea.png)

Just to add something to the loop, the error is still present if you try to update to "RM0228-123**5**-0.78.2-5eb5e99" (That update file is where the GitHub hyperlink takes you to when you press "WEB INSTALLER" in the release of "RM0228-123**6**-0.78.2-5eb5e99"):
![image](https://user-images.githubusercontent.com/19720181/222476851-0695a787-ba42-4357-91d6-cd58cd7b2231.png)

**Comment by RogueMaster** [comment]
Oops, I see, fixed so both will work

**Comment by MoScammin** [comment]
nope still same issue
