### ISSUE TITLE
Infrared - Learn New Remote Issue

### ISSUE THREAD

**Issue by m5performance** [RogueMaster/flipperzero-firmware-wPlugins#547]
When trying to learn new remote Flipper zero is picking up random IR Signals even if no external IR remote is being pressed or external signal is sent. 

To replicate the issue:

1- Go to Infrared app.
2- Select either Learn New Remote or Learn New Remote Raw.
3- as soon as you select one of the two options mentioned above almost immediately random signals start to get picked up.

P.S.
Thank you so much for moving the Infrared back to internal, the speed is greatly improved. Thank you for your efforts.

**Comment by RogueMaster** [comment]
Hi! Can you please attempt this on the original firmware? issue should be the same.
