### ISSUE TITLE
SubGhz: Transmission is blocked

### ISSUE THREAD

**Issue by andrearizzello** [RogueMaster/flipperzero-firmware-wPlugins#548]
Hello, i've just updated my flipper from 0.74.3 to latest version 0.78.2 and now when i open a subghz saved sequence it says that  Transmission is Blocked, frequency is outside of default range.
I guess it's a bug because it was working fine before or something has changed and i didn't find what

**Comment by RogueMaster** [comment]
Use Extend Range app to ignore default frequencies...
