### ISSUE TITLE
Dont delete custom animation manifest file

### ISSUE THREAD

**Issue by alvarotorijano** [RogueMaster/flipperzero-firmware-wPlugins#551]
### Description of the feature you're suggesting.

As user I don't want to be forced to rebuild my manifest for the desktop animations every time I install a new release from this repo. Is it possible to avoid this file to be overwritten during the installation?

**Comment by RogueMaster** [comment]
This is a behavior adopted from the original firmware, it is not considered an issue. However, I may do something for next release to help with this...

**Comment by RogueMaster** [comment]
Ok, next release will have something for you... thank you for contributing for the community!

https://github.com/RogueMaster/flipperzero-firmware-wPlugins/commit/cf4907a867c73830f299ec7328ff7b7c1c90204b

**Comment by RogueMaster** [comment]
Looks like the new no animation build has a default to internal and doesn't use the manifest on the SD card for some reason... would be changes that were added by OFW not allowing it... not sure how to fix but open to PR requests
