### ISSUE TITLE
NOANIMATION

### ISSUE THREAD

**Issue by alvarotorijano** [RogueMaster/flipperzero-firmware-wPlugins#552]
### Describe the bug.

This commit https://github.com/RogueMaster/flipperzero-firmware-wPlugins/commit/cf4907a867c73830f299ec7328ff7b7c1c90204b is breaking the animations. 
After installing the original manifest.txt file in the dolphin folder is lost.

### Reproduction

Intall the NOANIM distributed package via web o via flipper.

**Comment by RogueMaster** [comment]
Yes, this behavior is unwanted. I already reported it in the other thread so I'm aware. However, not sure how to fix it as the code involved came from main firmware. If you have any suggestions, I would welcome your PR. I'm not planning to spend time on it though. Busy with other projects (flipper and not) and tax season is upon us.
