### ISSUE TITLE
Add modified wifi marauder companion to firmware

### ISSUE THREAD

**Issue by LowSkillDeveloper** [RogueMaster/flipperzero-firmware-wPlugins#555]
### Description of the feature you're suggesting.

Add modified version of wifi marauder companion to receive sniffed packets via serial. That allows you to save caught packets to a memory card inserted into the flipper itself.
https://github.com/tcpassos/flipperzero-firmware-with-wifi-marauder-companion/releases/tag/0.3.1

modified firmware for wifi board here:
https://github.com/tcpassos/ESP32Marauder

i install it, but without a modified wifi marauder companion, it will not be save pcap files to the built-in memory card slot. The compiled fap file does not work in custom firmware. Maybe someone can do it?

**Comment by RogueMaster** [comment]
Added, Thank you!
