### ISSUE TITLE
Sub-GHz file name generation bug

### ISSUE THREAD

**Issue by LowSkillDeveloper** [RogueMaster/flipperzero-firmware-wPlugins#556]
### Describe the bug.

Sometimes a bug happens when you try to save the recorded file in "Read RAW" mode, it cannot be saved and gives the error "Cannot rename file / directory". But in fact, the file has been saved, but with the "old generated name", which is generated on the stock firmware. Below I will show what I mean.
And this problem is relevant only for RogueMaster firmware.
For records less than 30 seconds, the bug does not appear constantly, but it does. And if you record "Read RAW" for more than 30 seconds, the bug always appears. I already wrote about this once and I was on the right way.

What a normal record and name generation looks like:

1. Write a small file
![Screenshot-20230312-085155](https://user-images.githubusercontent.com/25121341/224532453-aa9727e1-7e87-458f-83fb-694703b45562.png)

2. Save it. And we generate a file name with a date.
![Screenshot-20230312-085158](https://user-images.githubusercontent.com/25121341/224532468-c3241634-8b77-49e3-bf02-9692dd216179.png)

3. Click save. And the file is saved successfully.
![Screenshot-20230312-085200](https://user-images.githubusercontent.com/25121341/224532472-03e475de-cbfb-4a30-aeaf-3103f9afeb22.png)

4. We check in the explorer. The file is present and has the same name that we generated and displayed on the screen.
![Screenshot-20230312-085238](https://user-images.githubusercontent.com/25121341/224532481-d1061a8b-4acd-47c4-a85f-5c3d7e74e12f.png)

**Now let's see what happens when we get the "Cannot rename file / directory" error.**

1. We write a large file in order to get an error for sure.
![Screenshot-20230312-085333](https://user-images.githubusercontent.com/25121341/224532486-cb14629b-7029-4d9a-8cb5-45c7863f5b2a.png)

2. Save it. And we generate a file name with a date. As usual. But...
![Screenshot-20230312-085337](https://user-images.githubusercontent.com/25121341/224532637-83a3f786-fab8-4f69-8812-204ee755cf67.png)

3. Click save. And the file is not saved. and throws a "Cannot rename file / directory" error.
![Screenshot-20230312-085339](https://user-images.githubusercontent.com/25121341/224532500-690d6368-a3a8-4b87-ae3e-805bedefefac.png)

4. Now the most interesting. We check the folder in the explorer and see that we have a file with a stock generated name, and not the new one that is used in RogueMaster. This is the same big file that we recorded and it is fully functional.

![Screenshot-20230312-085400](https://user-images.githubusercontent.com/25121341/224532541-430ef9be-9c1f-4778-99bf-a066d1acf312.png)

![Screenshot-20230312-085412](https://user-images.githubusercontent.com/25121341/224532544-f2fade8f-7176-446f-a311-88e5ef5d04b6.png)

The problem is in generating the name on save, this explains why there is no problem in stock and Unleashed. There is always a name generated in stock format.

### Reproduction

1. Write a long file
2. Try save
3. Get error
4. Look at folder and find a saved file but with a different name.

**Comment by RogueMaster** [comment]
This should fix it to use the OFW function that got created...

https://github.com/RogueMaster/flipperzero-firmware-wPlugins/commit/eb527c3130b871528ca86b791890882fcf9b4d5f

Thank you!
