### ISSUE TITLE
Error #[9-0]

### ISSUE THREAD

**Issue by GikitSRC** [RogueMaster/flipperzero-firmware-wPlugins#568]
### Describe the bug.

When I unzip the release, put it in the Updates folder of my Flipper Zero, and open the update file from my Flipper, it gives me the error:

**Update Failed!**
Error #[9-0]
OK to retry, hold back to abort

Can anyone help? I'm updating from the stock firmware and I have deleted my apps folder.
And when I try to flash the .tgz file from my computer, it said "Mainfest not found" or something like that

### Reproduction

1. Update to latest version of official firmware
2. Unzip the RogueMaster firmware and put in updates folder
3. Delete apps folder
4. Go back to Flipper, press down in desktop, choose the update folder, choose RogueMaster, then click on update then open in app
5. Error occurs

### Target

Updating 

### Logs

```Text
Where do I find the logs?
```

**Comment by RogueMaster** [comment]
You may have an issue with your SD card, you can install the .dfu file via Install From File option on qFlipper and extact SD Card Assets manually from the resources.tar file on the release.
