### ISSUE TITLE
CLI-GUI Bridge Chat Command

### ISSUE THREAD

**Issue by lp36000** [RogueMaster/flipperzero-firmware-wPlugins#579]
### Describe the bug.

For some reason when I use the CLI-GUI Bridge and run the chat command in this release it says  "Other application is running, close it first. Any ideas on this? 

### Reproduction

Just run the chat command in the CLI-GUI Bridge and it should gripe that another application is running

**Comment by RogueMaster** [comment]
Try closing terminal, qflipper or phone app; or restart the device
