### ISSUE TITLE
CO2 sensor app

### ISSUE THREAD

**Issue by kulikov91** [RogueMaster/flipperzero-firmware-wPlugins#582]
### Describe the enhancement you're suggesting.

Hi! 
Do you plan to add this app to firmware? 
https://github.com/thzinc/flipperzero-firmware/releases/tag/0.0.1%2Bupstream-0.75.0
Or something similar?

**Comment by RogueMaster** [comment]
Please correct me if I am wrong but I think that apps functions are implemented as the link below from someone else...

https://github.com/RogueMaster/flipperzero-firmware-wPlugins/tree/420/applications/external/scd30

If you have tested both and think that this one is better, please let me know...
