### ISSUE TITLE
CLI-GUI Bridge

### ISSUE THREAD

**Issue by lp36000** [RogueMaster/flipperzero-firmware-wPlugins#588]
### Describe the bug.

Hey guys, I have been doing some testing and I am pretty sure there is a real issue here. The problem is if you open the cli-gui bridge app from the flipper itself NOT connected to anything and run the chat command it will gripe that another application is running. But if i connect the flipper via usb and open a serial session with putty and issue the chat command it works with no problem. I have tried this through 2 firmware revisions, cold boots and have confirmed this behavior on 2 other units aside from mine. This used to work about 3 or 4 revs back. Any chance you guys can look into this please? The issue is easy to reproduce.

### Reproduction

Just launch the cli-gui bridge app from the flipper itself NOT connected to anything and run the chat command the message that another application is running will appear. But if you launch the chat command from a serial terminal (putty) via usb it works.

### Target

Flipper zero cli-gui bridge

### Anything else?

Thank you guys for all you do for the Flipper community I personally appreciate it.

**Comment by RogueMaster** [comment]
I undid chat changes and it still has issues, this must be an issue stemming from recent changes to RPC or other changes in OFW. Not sure how to fix...

**Comment by RogueMaster** [comment]
Fixed on latest release
