### ISSUE TITLE
mbus reading tools

### ISSUE THREAD

**Issue by utenus** [RogueMaster/flipperzero-firmware-wPlugins#589]
### Description of the feature you're suggesting.

It would be useful to add tools that would allow you to clearly read data from the mbus protocol, e.g. from water meters.

https://github.com/xaelsouth/rtl-wmbus
https://github.com/wmbusmeters/wmbusmeters

**Comment by qqmajikpp** [comment]
that sounds like a great idea. Good luck working on that. The community welcomes all hobby developers.
