### ISSUE TITLE
Setting to activate app layout like XFW and BAD KB

### ISSUE THREAD

**Issue by Jayvolution** [RogueMaster/flipperzero-firmware-wPlugins#591]
### Description of the feature you're suggesting.

Setting to activate app layout like XFW and BAD KB

https://cdn.discordapp.com/attachments/1056379877332353134/1086094225818538094/IMG_20230315_034511.jpg

**Comment by RogueMaster** [comment]
You are welcomed to PR this feature... it not, eventually, it may get worked in...
