### ISSUE TITLE
CLI-GUI Bridge

### ISSUE THREAD

**Issue by lp36000** [RogueMaster/flipperzero-firmware-wPlugins#592]
### Describe the bug.

Hey guys we have the same issue with the CLI-GUI bridge. If you launch the CLI-GUI Bridge application from the flipper itself, not connected to anything and run the chat command, it states that another application is running and wont let the command complete. But if you run it from a serial terminal (Putty) the chat command runs fine.

### Reproduction

If you launch the CLI-GUI Bridge application from the flipper itself, not connected to anything and run the chat command, it states that another application is running and wont let the command complete. But if you run it from a serial terminal (Putty) the chat command runs fine.

### Target

Flipper Zero latest firmware 2023-04-10

### Anything else?

Again thank you guys for all you do. :)

**Comment by RogueMaster** [comment]
Latest Patreon release has this fixed

**Comment by RogueMaster** [comment]
Feel free to compile from code if you don't have access to the release

**Comment by ranchordo** [comment]
I also fixed the app over on [ranchordo/flipperzero-cli-bridge](https://github.com/ranchordo/flipperzero-cli-bridge) with release v1.2, sorry it took me a while to get to fixing this.
