### ISSUE TITLE
Lefty mode controls inverted

### ISSUE THREAD

**Issue by INSANEMODE** [RogueMaster/flipperzero-firmware-wPlugins#593]
### Describe the bug.

If you switch to lefty mode, the screen is oriented correctly (flipped), but the directions are incorrect.
 Pressing down scrolls up, pressing right goes left, etc.
This happens on latest github release 1af0221 and when compiling 468b33556ce373c52dde1aab0664e019b3ab8c61 .

Issue did not occur with unleashed a524fd7 / unlshd-042.

### Reproduction

1. switch on
2. settings
3. system
4. change hand orient to lefty
5. press any directional buttons

**Comment by RogueMaster** [comment]
Hi! This feature came from OFW. I have tested on OFW and it has the same issue there. Please open an issue with OFW so they can fix.
