### ISSUE TITLE
Flipper won’t boot and blinks after update 

### ISSUE THREAD

**Issue by FoxLy1312** [RogueMaster/flipperzero-firmware-wPlugins#606]
### Describe the bug.

New building wont boot and needed dfu repair sequence to recover twice. 

### Reproduction

Build Repo
Updated to current official Software
Delate Apps folder 
Browse  and install RM-update
?
Blinking Boot loop
Repeat

**Comment by RogueMaster** [comment]
This is fixed on latest code for the time being... the cause of the radio FW update causing the boot loops is still unknown...
