### ISSUE TITLE
 Pokemon Trading leads to (null reference?) crash

### ISSUE THREAD

**Issue by VoltaicGRiD-Canon** [RogueMaster/flipperzero-firmware-wPlugins#613]
### Describe the bug.

Examining the applications available, saw the Pokemon trader and decided to look through it. Clicking anything other than back or left, right crashed the Flipper.

### Reproduction

1. Main Menu >
2. Applications >
3. GPIO >
4. Pokemon Trading
5. Press OK or Up or Down

### Anything else?

Will investigate logs if I can find them, but had to restore stock firmware in order to reboot.

**Comment by RogueMaster** [comment]
This should be fixed for future builds
