### ISSUE TITLE
Allow changing the CE and CSN pin mappings for the NRF24 peripheral

### ISSUE THREAD

**Issue by ozgunawesome** [RogueMaster/flipperzero-firmware-wPlugins#615]
### Description of the feature you're suggesting.

If the CE and CSN pin assignments can be changed, we could have multiple SPI peripherals connected to the SPI bus of the F0. The SPI protocol allows for more than one slave as long as they use different chip enable pins.

Currently the docs suggest 4/A4 for CSN and 6/B2 for CE.

My proposal is to make this assignment adjustable from somewhere (could be in-app, or in Settings, or even a configuration file)

This would allow for more complex addon boards to be built (such as NRF24 + external CC1101 or ext CC1101 + two CAN buses on the same board)

**Comment by RogueMaster** [comment]
This is not an issue to the firmware but a new feature you want to create. Thank you for the suggestion, hopefully you or someone else can develop this feature. Please make a fork and develop your solution and submit PR for review. Sounds like it can be useful.
