### ISSUE TITLE
Subghz error

### ISSUE THREAD

**Issue by Hitmanreis** [RogueMaster/flipperzero-firmware-wPlugins#616]
### Describe the bug.

Why does it crash when I enter and exit Sub Ghz more than once?

https://youtube.com/shorts/nHUoJRY3u2Y?feature=share

### Reproduction

Open close

### Target

Subghz

**Comment by RogueMaster** [comment]
Video is removed and unable to replicate issue on latest release

**Comment by Hitmanreis** [comment]
friends who have the same problem, I solved the problem by plugging the pins into 3v input instead of 5v, I am attaching a photo

![Screenshot_2023-05-03-21-46-49-490_com google android youtube](https://user-images.githubusercontent.com/131968292/236025146-64c51fdc-d516-4410-8048-4a22f542cf48.jpg)
