### ISSUE TITLE
API Mismatch and BadUSB/Bad BT not working

### ISSUE THREAD

**Issue by grugnoymeme** [RogueMaster/flipperzero-firmware-wPlugins#622]
### Describe the bug.

Hello i built just now with ./fbt the fw but when i oush right arrow to see the passport, it result me API mismatch bla bla u want to continue?
and when i try open bad usb it returns "ERROR Preload failed INVALID FILE"

### Reproduction

Hello i built just now with ./fbt the fw but when i oush right arrow to see the passport, it result me API mismatch bla bla u want to continue?
and when i try open bad usb it returns "ERROR Preload failed INVALID FILE"

### Target

Bad USB / Passport

### Anything else?

no..

**Comment by grugnoymeme** [comment]
installing the 508 via updater is working fine i dont know why

**Comment by grugnoymeme** [comment]
ok maybe the problem is that i used ./fbt flash_usb that's not working with rm right?

**Comment by RogueMaster** [comment]
No, it doesn't install apps on any firmware. You installed incorrectly and did not follow the instructions in the Read Me
