### ISSUE TITLE
BadUSB and U2F stop functioning in 0.60.3-556af0b8-0621-RM

### ISSUE THREAD

**Issue by calrblmss** [RogueMaster/flipperzero-firmware-wPlugins#63]
Hey all, I'm having a few missing features with the new 0.60.3-556af0b8-0621-RM. BadUSB and U2F seem to have disappeared from the menu and nothing happens when I try to run them from the browsing menu.

Upon reflashing to the current official firmware they appear and work again, and going back to 0.60.3-556af0b8-0621-RM they once again disappear and don't work.

I'm seeing this as similar to issue #58, but given it is also missing U2F, I thought I would open a new issue. Hopefully this one isn't too bad.

Target: BadUSB, U2F

**Comment by RogueMaster** [comment]
This is now fixed in the code and a new release will be put out shortly
