### ISSUE TITLE
upgrade failed with RM0512-1442-0.83.1-f0144d7

### ISSUE THREAD

**Issue by Shocktrooper** [RogueMaster/flipperzero-firmware-wPlugins#631]
### Describe the bug.

When trying to use the web installer with animations the flipper has a screen at the end of the process saying the update failed for the latest release `RM0512-1442-0.83.1-f0144d7`

### Reproduction

Go to releases page
Click web installer
proceed to try and install latest firmware

**Comment by RogueMaster** [comment]
I tried to replicate your issue to no avail. Please try again. If your problem persists, install the latest OFW dev and then upgrade to the latest [RM release](https://lab.flipper.net/?url=https%3A%2F%2Frogue-master.net%2F%3Ffile%3DRM0512-1442-0.83.1-f0144d7.tgz&channel=RM0512-1442-0.83.1-f0144d7&version=0.83.1).
