### ISSUE TITLE
Using playlists

### ISSUE THREAD

**Issue by ifuchs** [RogueMaster/flipperzero-firmware-wPlugins#635]
I am running RM and when I connect the F0 to Qflipper I can see .txt files in the SubGhz/Playlist folder but if I go to SubGhz->Saved/Playlist on the F0 directly, it is empty. How does one use a playlist?

**Comment by RogueMaster** [comment]
Subghz->Saved only shows .sub files that can be played with the SubGHz app. Try viewing the playlist files through the Browser or the SubGHz Playlist application
