### ISSUE TITLE
LCD Timeout and Auto-lock options should match

### ISSUE THREAD

**Issue by hasmar04** [RogueMaster/flipperzero-firmware-wPlugins#64]
**Is your feature request related to a problem? Please describe.**
Having the LCD timeout be able to line up with the auto-lock at all values would be really useful to know if the device has locked or not. Also 30s for the auto-lock is too long in my opinion. 

**Describe the solution you'd like**
Have the same time options available for both LCD timeout and auto-lock, but they can still be separate options. 

**Describe alternatives you've considered**
- Having the option to link them together, so changing one automatically changes the other. This would just require more effort. 
- Increasing the LCD timeout to the current minimum auto-lock time. This would significantly harm battery life.

**Comment by RogueMaster** [comment]
What options would you suggest be placed for each? I could add options to either I think

**Comment by hasmar04** [comment]
My suggestion was to make the options for both the same. So basically add whatever is in one which is not in the other.

**Comment by RogueMaster** [comment]
See changes [here](https://github.com/RogueMaster/flipperzero-firmware-wPlugins/commit/25b099bd133650b0485c974e05dafa5ca35fad35) and [here](https://github.com/RogueMaster/flipperzero-firmware-wPlugins/commit/f88044d5054eb7f9a8b31b3bc5543f243e2f56cc); no sense in adding auto-lock for 1s or 5s, 10s and 15s is pretty short.
