### ISSUE TITLE
Excess Desktop Settings Moved to CFW App ($25 ETH or BTC BOUNTY)

### ISSUE THREAD

**Issue by RogueMaster** [RogueMaster/flipperzero-firmware-wPlugins#640]
### Describe the enhancement you're suggesting.

Non-Stock Settings to a Desktop section in CFW (Including Game Mode)

### Anything else?

Make sure Passport(?), Dice and Clock view the new Game Mode settings. Keep favorites apps x4 with stock settings internal. This would fix issue with applications.h being used for external FAP and also favorite apps bug with icons missing for FAPs would go away.

 ($25 ETH or BTC BOUNTY) PR Submission and DM on Discord with wallet address.

**Comment by ZekePolarisBSH** [comment]
Is there a reason the PIN settings and everything under Desktop in the Flipper's settings always reset at random?

**Comment by RogueMaster** [comment]
> Is there a reason the PIN settings and everything under Desktop in the Flipper's settings always reset at random?

Welcome to Flipper Zero development. Get used to it. They keep changing things related to the settings this they do reset.

**Comment by ZekePolarisBSH** [comment]
Weird this happens without updates but I can get used to it. I just think of it as another relog from GTA5 servers.

**Comment by RogueMaster** [comment]
> Weird this happens without updates but I can get used to it. I just think of it as another relog from GTA5 servers.

Make sure you don't have a desktop settings file on your SD card settings folders... RM FW is using the internal location for desktop settings...

**Comment by RogueMaster** [comment]
@ESurge has completed this Bounty. ESurge confirm your BTC address on Discord DM for transfer
