### ISSUE TITLE
IR Remote (5V/External GPIO Settings in App Like Infrared) ($25 USD in ETH or BTC)

### ISSUE THREAD

**Issue by RogueMaster** [RogueMaster/flipperzero-firmware-wPlugins#641]
### Describe the enhancement you're suggesting.
Turn on 5V if IR settings is set to external device and 5V enabled.
Have GPIO Settings menu for IR Remote (Like Infrared)
Have Settings Menu Option appear upon exit scene (Like Remote apps)

### Anything else?
($25 USD in ETH or BTC) PR Submission and DM on Discord with wallet address.

If you are a Patreon supporter and would value this functionality, please DM on Patreon and I will add your monthly subscription to the prize allotment. If you have specific stipulations on how you want it to behave, feel free to detail them in a comment here for review.

**Comment by protocolpolice** [comment]
will try to merge  TV-B-Gone with flipper zero [check this](https://twitter.com/_ProtocolPolice/status/1658169304188084237?s=20)  also ..will need all the help you can find  *grin*   ref:  if this works we'll go for IR floodlights  LOL

**Comment by phr34k0** [comment]
Yeah as OP stated. I had troubles with this firmware but not Unleashed. Was trying to get my IR Blaster to work which it did not -> https://www.tindie.com/products/tehrabbitt/flipper-zero-ir-blaster/ as there was no 'set IR to external device'

**Comment by roguepullrequest** [comment]
> Yeah as OP stated. I had troubles with this firmware but not Unleashed. Was trying to get my IR Blaster to work which it did not -> https://www.tindie.com/products/tehrabbitt/flipper-zero-ir-blaster/ as there was no 'set IR to external device'

You need to enable debug in the device settings menu then if the option doesnt show up then reboot.

**Comment by RogueMaster** [comment]
After some testing, if GPIO gets 5V turned on, then IR Remote gets opened, it works perfect. So this issue is fixed I think... same behavior in RM and Unleashed... Also tested while viewing IR signal on phone camera and testing response from TV...

**Comment by RogueMaster** [comment]
Re-opened since although it is not broken, having it in the app would be nice...

**Comment by RogueMaster** [comment]
Best case, this scene can be added for the app... [infrared_scene_debug_settings](https://github.com/DarkFlippers/unleashed-firmware/blob/dev/applications/main/infrared/scenes/infrared_scene_debug_settings.c)

Perhaps Hold Back takes us to a menu to either Exit or GPIO Settings or Back To Remote... 

This would allow to enable 5V within app instead of having to exit and go to GPIO first...

**Comment by RogueMaster** [comment]
@Hong5489 or @d4ve10 could you help?

**Comment by RogueMaster** [comment]
If you are a Patreon supporter and would value this functionality, please DM on Patreon and I will add your monthly subscription to the prize allotment. If you have specific stipulations on how you want it to behave, feel free to detail them in a comment here for review.

**Comment by coolshrimp** [comment]
> Best case, this scene can be added for the app... [infrared_scene_debug_settings](https://github.com/DarkFlippers/unleashed-firmware/blob/dev/applications/main/infrared/scenes/infrared_scene_debug_settings.c)
> 
> Perhaps Hold Back takes us to a menu to either Exit or GPIO Settings or Back To Remote...
> 
> This would allow to enable 5V within app instead of having to exit and go to GPIO first...

has this been solved yet? if not i can add it.

**Comment by RogueMaster** [comment]
> has this been solved yet? if not i can add it.

It has not yet, please do :)
