### ISSUE TITLE
Add App to MainMenu and crash

### ISSUE THREAD

**Issue by Kzy07** [RogueMaster/flipperzero-firmware-wPlugins#643]
### Describe the bug.

Good evening, by looking in the new options, I found the possibility of adding App to the mainmenu, damage Flipper crash

https://www.mediafire.com/file/v6pz0294s53o6mj/IMG_0197.MOV/file

Crash : NULL pointer dereference

### Reproduction

1 CFW Settings
2 Interface
3 Mainmenu
4 Add App
5 ' Select App '
6 crash ' NULL pointer dereference '

### Target

Flipper

**Comment by RogueMaster** [comment]
This is fixed for next release.

**Comment by Kzy07** [comment]
I compiled it, it works perfectly. thank you nice work
