### ISSUE TITLE
Lock + OFF while charging waits for the device to be unplugged

### ISSUE THREAD

**Issue by sanderDijkxhoorn** [RogueMaster/flipperzero-firmware-wPlugins#646]
### Describe the bug.

I am not sure if this is expected behaviour or not but when the Flipper is plugged into my MacBook with or without the qFlipper app open and I click on the "Lock + OFF" button it waits for the cable to be unplugged until it actually turns off. I could see why you want this behaviour for if the qFlipper app or a browser is connected to the device but just charging is a bit odd, just want to make sure this is expected or not :)

### Reproduction

1. Plug your Flipper intro your PC (I was using a M1 MacBook Pro (USB-C -> USB-C)
2. Navigate & click on the "Lock + OFF"
3. You see the lock animation but it won't turn off the device.

### Anything else?

I am on the latest version as of writing this. ([RM0518-2052-0.83.2-8197480](https://github.com/RogueMaster/flipperzero-firmware-wPlugins/releases/tag/RM0518-2052-0.83.2-8197480))

**Comment by RogueMaster** [comment]
Unplug it to make it go away. This is behavior that comes from OFW and it isn't considered a bug.
