### ISSUE TITLE
Subghz-remote maker + brainfuck

### ISSUE THREAD

**Issue by grugnoymeme** [RogueMaster/flipperzero-firmware-wPlugins#657]
Hi i noticed that subghz-remote maker is creating nu remotes in a nu directory subghz-remote in the root of FLIPPER SD, this is adding to the old "subghz/remote" and "subghz/subghz-remote" it would be nice to save all the remotes in one directory.. just to not make confusion..
I also noticed that if u leave for about a minute the app "brainfuck" opened without typing anything, flipper crash, or stop working, better, and needs to be rebooted.
Thank u!! Bye!

**Comment by RogueMaster** [comment]
You have the remote folder from a different firmware... we use subghz_remote folder.

As for brainfuck, the app lives up to its name. Please inquire with [original developer](https://github.com/nymda/FlipperZeroBrainfuck) if issues are found.
