### ISSUE TITLE
Issue with Calculator 2?

### ISSUE THREAD

**Issue by ZekePolarisBSH** [RogueMaster/flipperzero-firmware-wPlugins#666]
### Describe the bug.

The multiplication on the app doesn't work. Try using any# times any#. It ignores the user. Calculator 1 works just fine though. Please add into FW update to prevent re-adding of deleted apps.

### Reproduction

Remove app
Install FW update
App gets auto added back
?

**Comment by RogueMaster** [comment]
Removed for next release
