### ISSUE TITLE
 External CC1101 Antenna Board 

### ISSUE THREAD

**Issue by lp36000** [RogueMaster/flipperzero-firmware-wPlugins#667]
### Describe the enhancement you're suggesting.

So I found this by accident but I am hoping it can be taken advantage of. When you plug in a 
External CC1101 Antenna Board via GPIO and go into Subghz and turn on the external antenna it works fine. But when you exit the Subghz menu it will revert back to the internal antenna (which was expected) However.... if the Flipper is just simply plugged into USB on anything etc: a PC a Phone it does not matter and does not have to be an RPC connection either,  and you go into the Subghz menu and turn on the external antenna, and exit the subghz menu the external antenna will STAY selected and enabled. This is very handy so it can be utilized by the Subghz chat CLI and the Pager, it can also be used with playlists and the Subghz remote app. If you guys can figure out a way to keep the external antenna selected and active when backing out of the Subghz menu without being connected to USB that would be very handy. Thanks again for your time and keep up the fantastic work!!!

**Comment by ESurge** [comment]
From my experience, once you've connected the External CC1101 module and enabled it in SubGHz settings, it applies system wide for all SubGHz apps. I use an external CC1101 module with the Weather app all the time.

I think if the connection to the external CC1101 module is disconnected physically, it'll revert to the internal CC1101 whenever the next SubGHz app is run.
