### ISSUE TITLE
Something happened

### ISSUE THREAD

**Issue by ZekePolarisBSH** [RogueMaster/flipperzero-firmware-wPlugins#675]
### Describe the bug.

Was working just fine and then out of no where it reverted back to dev but claims to be RM and it isn't letting me run any updates and all the tools are gone. I didn't do anything for this to happen. Any ideas?

### Reproduction

Normal use

**Comment by RogueMaster** [comment]
Sounds like you are in game mode... What happens exactly when you press up and when you press left?

**Comment by ZekePolarisBSH** [comment]
> Sounds like you are in game mode... What happens exactly when you press up and when you press left?

No that is not the case. It deleted everything including the folder that holds all that is RogueMaster. Gamemode is off.

**Comment by ZekePolarisBSH** [comment]
Nothing happens when I press left btw.
