### ISSUE TITLE
CLI-GUI Bridge Crash

### ISSUE THREAD

**Issue by lp36000** [RogueMaster/flipperzero-firmware-wPlugins#677]
### Describe the bug.

The CLI-GUI Bridge crashes with a null pointer refrence when exiting the chat everytime. I have confirmed this on 3 other devices.

### Reproduction

Open the GUI-CLI Bridge app from the flipper itself. Issue the chat command. Exit the app and it will crash with a null pointer refrence.

### Target

FLipper Zero RM0625-1154-0.85.3-4f7f5a5  and previous rev

**Comment by RogueMaster** [comment]
So chat actually works then? The issue is after runtime? This is a non-essential bug but it shall be looked into

**Comment by lp36000** [comment]
Correct, the Chat appears to work, it is when exiting the cli-gui bridge app after chat

**Comment by RogueMaster** [comment]
This is now fixed
