### ISSUE TITLE
 That's compile ERRORS

### ISSUE THREAD

**Issue by cokyrain** [RogueMaster/flipperzero-firmware-wPlugins#682]
### Describe the bug.

sh: 1: ./scripts/fastfap.py: Permission denied
scons: *** [build/f7-firmware-C/.extapps/Plantower_PMSx003_Sensor_Reader.fap] Error 126

********** FBT ERRORS **********
build/f7-firmware-C/.extapps/Plantower_PMSx003_Sensor_Reader.fap: Error 126
Error: Process completed with exit code 2.

### Reproduction

in ubuntu 23.04

**Comment by RogueMaster** [comment]
Pull latest updates and this should be fixed.

**Comment by cokyrain** [comment]
> 

it's ok,  thank you
