### ISSUE TITLE
#675

### ISSUE THREAD

**Issue by ZekePolarisBSH** [RogueMaster/flipperzero-firmware-wPlugins#684]
### Describe the bug.

Need more help I was late to reply and is already closed before I got to answer. GitHub did not notify me that you replied. It is not in game mode and nothing happens when I press left. It deleted everything out of no where and because of this I am forever locked out of all of my accounts...

### Reproduction

#675

**Comment by RogueMaster** [comment]
Also, pressing left needs to be assigned under Desktop Primary Favorite
