### ISSUE TITLE
Subghz question

### ISSUE THREAD

**Issue by Xbxjdjdjd** [RogueMaster/flipperzero-firmware-wPlugins#690]
### Description of the feature you're suggesting.

Is there a way to add specific subghz frequencies? I have a weather station that operates on exactly 433 mhz but flipper can’t transmit/read exactly 433 mhz

**Comment by RogueMaster** [comment]
I think you may have to create a protocol for it if its not supported, but ask Skorpion on official discord, he created the app and may know best...
