### ISSUE TITLE
IR camera

### ISSUE THREAD

**Issue by Xbxjdjdjd** [RogueMaster/flipperzero-firmware-wPlugins#691]
### Description of the feature you're suggesting.

A camera functioning off of the built in infrared module, such as a security camera with that IR ring to see in the dark. (If possible)

**Comment by RogueMaster** [comment]
Ring cameras use infrared to light up the area, not as a camera. Camera based on wifi is possible from what I've heard recently.. feel free to submit a PR if you figure this out, please stop submitting these PR, feel free to use Discord...
