### ISSUE TITLE
IR motion sensor

### ISSUE THREAD

**Issue by Xbxjdjdjd** [RogueMaster/flipperzero-firmware-wPlugins#692]
### Description of the feature you're suggesting.

An infrared motion sensor that alerts you when an infrared beam is broken. This beam should be sent out via the onboard infrared module. If this feature is added, you could stick some reflective tape somewhere and the flipper can read that the beam is being sent back. When broken it could vibrate and make a beep, or maybe a ding dong like a door sensor.

**Comment by RogueMaster** [comment]
Open to the feature. Please submit PR if you figure out how to do it... in the meantime, this isn't what our issues are used for...
