### ISSUE TITLE
Buttons do not work when using RM firmware

### ISSUE THREAD

**Issue by Jdjdis** [RogueMaster/flipperzero-firmware-wPlugins#701]
### Describe the bug.

When you go install RougeMaster without animations, you are unable to use the buttons, and makes the flipper unusable 

### Reproduction

1. Install rouge master without animations

**Comment by RogueMaster** [comment]
There may have been an issue with your installation, please install again.

**Comment by Jdjdis** [comment]
I have reinstalled 5 times, and same issue

**Comment by RogueMaster** [comment]
Try a different installation method maybe? How are you installing? I have installed the GitHub release No Animations and the Patreon release 2 times each and both are working upon install.

**Comment by Jdjdis** [comment]
Installing on GitHub, via web installer. I also just installed using .fap
file and same error.

**Comment by RogueMaster** [comment]
FAP files don't install the firmware... FAP files should just be used out of the firmware they are made for... also... web installer on GitHub for No Animations build is fully working and tested three times now...
