### ISSUE TITLE
Flipper crashed and was rebooted (frui_check failed)

### ISSUE THREAD

**Issue by cokyrain** [RogueMaster/flipperzero-firmware-wPlugins#703]
### Describe the bug.

Use flipper app connected to flipper , enter a sub-ghz in archive and press send ,then the flipper crashed

### Reproduction

Use flipper app on ios, and firmware compiled from commits on Jul 11 and then on,

**Comment by cokyrain** [comment]
furi_check failed

**Comment by RogueMaster** [comment]
So this issue only happens when you are accessing through the app?

**Comment by cokyrain** [comment]
> 
yes, it's only crash through the app. Direct operation on the machine without failure

**Comment by cokyrain** [comment]
It's crashed at send sub-ghz when connected to mobilephone through bluetooth every time

**Comment by cokyrain** [comment]
> This will be reviewed further

After testing, It's crashed through the app to send sub-ghz, and causes the file 'SDCard/subghz/assets/setting_user.txt’ to be emptied. Then after the flipper reboot , it's crashed everytime when send sub-ghz without mobilephone connected.
