### ISSUE TITLE
Shutdown on Idle affects update screen

### ISSUE THREAD

**Issue by DarkEnder4583** [RogueMaster/flipperzero-firmware-wPlugins#711]
### Describe the bug.

The Shutdown on Idle feature counts the time spent on the update screen as idle, resulting in failed updates

### Reproduction

1. Set “Shutdown on Idle” to 15 min
2. Connect to Flipper via Mobile App
3. Begin update process
4. (Hope it takes longer than 15 minutes to update)
5. Flipper shuts down and the update will fail

**Comment by RogueMaster** [comment]
1. Set “Shutdown on Idle” to 15 min <--- Don't do this part and you won't run into this issue 😓

**Comment by DarkEnder4583** [comment]
Well, I figured that much, and that is what I did to work around the bug. Just thought you wouldn't want to settle for a workout, but aiight.

It would be nice if it was at least noted somewhere, cause it took me an embarrassingly long time to realize that's what was failing my updates.
