### ISSUE TITLE
Protocol Princeton 24 bits emulation does not work correctly (others probably fail too)

### ISSUE THREAD

**Issue by 54m0hT** [RogueMaster/flipperzero-firmware-wPlugins#712]
**Describe the bug.**

When Flipper receives and decodes what Flipper says to be a princeton 24 bit code, the data appears correctly, but when emulating it does not work. If you record the same signal with the RAW method it works correctly. I have also tried in Keeloq Dea_Mio and Nice Flor-S system with known key and also fails. Possible file/code emulation problem?

**Reproduction**

- Subghz - Read.
- Press Remote Control with Princeton Code
- When the read code appears, emulate or save and then emulate.

**Target.**

0.86.3 firmware

**Comment by RogueMaster** [comment]
Switching to internal to help other problem which could help this one... it is also possible signal is not fully supported due to actual protocol used by sending remote... glad you can have it work RAW... you should use that for this signal...
