### ISSUE TITLE
ESP32 Evil Portal crashes upon open

### ISSUE THREAD

**Issue by Jdjdis** [RogueMaster/flipperzero-firmware-wPlugins#719]
### Describe the bug.

When opening ESP32 Evil Portal, with the board plugged in, Flipper crashes and reboots with the error NULL pointer dereference.

### Reproduction

1. Plug in WiFi board
2. Turn on flipper
3. Press the center button 
4. Scroll to applications, and click
5. Scroll to GPIO, and click
6. Scroll to [ESP32] Evil Portal
7. Click start portal
8. Flipper will crash

**Comment by RogueMaster** [comment]
Flash the evil portal onto your ESP32 and don't open ticket issues because you don't know better... read the documents and learn how to make it work.
