### ISSUE TITLE
SubGhz not adding frequencies with external antenna 

### ISSUE THREAD

**Issue by Foul** [RogueMaster/flipperzero-firmware-wPlugins#728]
### Describe the bug.

I added recently an ESP32-Wroom to expend his capabilities, ESP seems to work fine, external antenna is recognized but when using SubGhz app, frequencies are not added like the internal antenna do. I hear the sound, but nothing appear.. see video attached.

### Reproduction

Latest RM
Latest Esp-marauder flashed

### Anything else?

Video to help: https://cdn.discordapp.com/attachments/1095048959153672232/1137656072031715399/VID_20230806_095557.mp4

**Comment by RogueMaster** [comment]
The external antennas improve sending of signals. receiving signals should be done with internal antenna since it will provide better signal recording
