### ISSUE TITLE
Authenticator fails to load due to missing config file

### ISSUE THREAD

**Issue by s1shed** [RogueMaster/flipperzero-firmware-wPlugins#733]
### Describe the bug.

After  updating to `RM0815-0250-0.89.1-67fe5f9`  the Authenticator fails to load, returning an error that the config file cannot be found. I don't know when the regression was introduced.

The authenticator had already been configured.

### Reproduction

1. Go to Apps → Tools → Authenticator
2. See error

### Anything else?

I was able to fix the error by renaming `apps_data/authenticator`  to `apps_data/totp`.

**Comment by RogueMaster** [comment]
This is fixed for next release
