### ISSUE TITLE
Lefty Settings

### ISSUE THREAD

**Issue by AudriusUp2Me** [RogueMaster/flipperzero-firmware-wPlugins#737]
### Describe the bug.

is needed to revert direction buttons on Hand Orient lefty.

### Reproduction

1. Settings
2. System
3. Hand Orient -> Lefty

**Comment by RogueMaster** [comment]
It's already in the firmware

**Comment by AudriusUp2Me** [comment]
Sorry for the misunderstanding. Lefty settings are in the firmware, you are
true. But directions for control are wrong. Pushing Down button, going Up,
and pushing Up, Going Down. I'm using RM0825-0241-0.90.1-31ce030-NoAnim.tgz

Best Regards

2023-08-20, sk, 21:15 RogueMaster ***@***.***> rašė:
