### ISSUE TITLE
The app is stuck on syncing 

### ISSUE THREAD

**Issue by cokyrain** [RogueMaster/flipperzero-firmware-wPlugins#740]
### Describe the bug.

The flipper0 flashed the latest firmware.  The Flipper app spends a lot of time on syncing everytime when flipper0 connected to mobile. When the synchronization is complete, it will repeat syncing work after close the app and reopen it.

### Reproduction

1.Flash the latest firmware (Versions after August 15th)
2.Open the Flipper app
3.Connent the device
4.It spends a lot of time on syncing

**Comment by RogueMaster** [comment]
This repo is not for the app
