### ISSUE TITLE
[NFC] Read new tag using keys from another saved dump

### ISSUE THREAD

**Issue by ste94pz** [RogueMaster/flipperzero-firmware-wPlugins#742]
### Describe the enhancement you're suggesting.

It would be good to have the ability to read a tag choosing a saved dump as source for the keys to unlock it, instead on waiting the dictionary attack to pick the correct keys from the user dictionary.

**Comment by RogueMaster** [comment]
I am open to a PR for this. Please re-open as a PR with the code.
