### ISSUE TITLE
NFC can't save on device

### ISSUE THREAD

**Issue by hrco69** [RogueMaster/flipperzero-firmware-wPlugins#746]
### Describe the bug.

I try to read nfc, it reads it normaly and then i try to save it but it does not allow me. Error says "Can not save key file". 

### Reproduction

1. scan NFC
2. save NFC
3. error

**Comment by hrco69** [comment]
it was ISO 15693 and it cant be saved on flipper

**Comment by RogueMaster** [comment]
If it doesn't work for saving for ISO15693 and you need it, you are welcomed to PR a solution when found
