### ISSUE TITLE
External sub-ghz module option not available 

### ISSUE THREAD

**Issue by jetlagv1** [RogueMaster/flipperzero-firmware-wPlugins#748]
### Describe the bug.

Switching to the external sub-ghz module not available in the menu with latest roguemaster version. After switching to default flipper firmware version 0.91.4 it works but when changing back to roguemaster it is again not available. 

### Reproduction

1 Connect external c1011 module
2 power on flipper
3 go to sub-ghz menu
4 select Radio setting
5 first item is Module which is set to internal and external is not available.

**Comment by ESurge** [comment]
This option is stuck on `Internal` if the external CC1101 module isn't connected properly or perhaps if the `SPI CC110 Handle` pin option isn't set correctly in `CFW Settings` app > `Protocols` menu

If you had the SPI CC1101 Handle option set to `Extra` and it wasn't supposed to be, and then changed it to `Default` while your external CC1101 module was still connected, chances are you'll need to power cycle your external module before it gets picked up by the SubGHz app.
