### ISSUE TITLE
Genie Door Recorder not starting, shows to update firmware, missing l-mports

### ISSUE THREAD

**Issue by darkmanlv** [RogueMaster/flipperzero-firmware-wPlugins#762]
### Describe the bug.

Running app Genie Door Recorder from Sub-GHz folder receive error:
"Update Firmware to use with this Application (Missingl-mports)"

Version of Roguemaster - RM1003-0047-0.92.3-0f6cbde

### Reproduction

1. run app Genie Door Recorder from Sub-GHz folder

**Comment by RogueMaster** [comment]
This will be fixed in a future release. Dev needs some time to work on the changes.
