### ISSUE TITLE
Chamberlain on 433mhz

### ISSUE THREAD

**Issue by geckom** [RogueMaster/flipperzero-firmware-wPlugins#763]
### Describe the bug.

when using the "Read" option under SubGhz, a chamberlain device running on 433Mhz isnt detected at all.

I brief look at the code shows it only detects on 315, however it can also run on 433 in EU.

### Reproduction

1. Find chamberlain device
2. Set flipper to read subghz
3. press button and observe nothing happens
4. save raw and confirm its chamberlain another way ie. Kaiju

**Comment by RogueMaster** [comment]
Please open this as an issue for OFW since those protocols initially came from there
