### ISSUE TITLE
Games to remove

### ISSUE THREAD

**Issue by RogueMaster** [RogueMaster/flipperzero-firmware-wPlugins#77]
## **POLL:**
- Option 1 Raycast [Heart Emoji]
- Option 2 Game of Life [Rocket Emoji]
- Option 3 Flappy Bird [Eyes Emoji]

**Comment by RogueMaster** [comment]
Heart+Rocket = 8KB

**Comment by RogueMaster** [comment]
games will stay in code but removed from meta/applications.fam

**Comment by UberGuidoZ** [comment]
Raycast is as close to Doom as we have... but I get it's "pointless" like game of life. But game of life COULD be good. Flappy Bird, to me, doesn't even work as you never die. If there was a challenge, I'd say keep it. But you can just go through walls. =P

**Comment by ESurge** [comment]
I say whichever combo is smallest until sd card loading is ready. :)

**Comment by theryex** [comment]
You could always make a second build with zero games for more features, until SD loading that is.

**Comment by pingywon** [comment]
> Raycast is as close to Doom as we have... but I get it's "pointless" like game of life. But game of life COULD be good. Flappy Bird, to me, doesn't even work as you never die. If there was a challenge, I'd say keep it. But you can just go through walls. =P

Conway's Game Of Life is a hacker classic though.... :*( 

My vote is for raycast. It just doesnt do it for me. It is great but it tries to be too much on a limited platform. my 2 cents

**Comment by RogueMaster** [comment]
Surprisingly, flappy really got the axe. I have axed all 3 right as it is needed with the latest updates. Can't wait for SD loading! May add Chess to test and compile and hide it...

**Comment by RogueMaster** [comment]
> You could always make a second build with zero games for more features, until SD loading that is.

This can easily be done by compiling with a meta file without games, I have no interest in compiling a boring firmware without the games...
