### ISSUE TITLE
StatusBar drawn on menus

### ISSUE THREAD

**Issue by LeeroysHub** [RogueMaster/flipperzero-firmware-wPlugins#772]
### Describe the bug.

If Clock is enabled on desktop, it draws on power menu and up arrow shortcut menu.

I added this code to gui.c to fix.

static void gui_redraw_status_bar(Gui* gui, bool need_attention) {
    ViewPortArray_it_t it;
    uint8_t left_used = 0;
    uint8_t right_used = 0;
    uint8_t left_slim_used = 0;
    uint8_t right_slim_used = 0;
    uint8_t top_used = 0;
    uint8_t width;

    //We dont want to draw the status bar if its hidden.
    if(gui->hide_statusbar_count > 0) {
        return;
    }

### Reproduction

1. Enable Clock
2. Hold back t power off and view clock!

**Comment by RogueMaster** [comment]
Thank you! Will add

**Comment by Hellblocc600** [comment]
Quick question does the newest update has android BLE spam

**Comment by LeeroysHub** [comment]
Yes, the Apple BLE Spam app is included. There is no Android BLE Spam, just Apple.


-------- Original message --------
From: Hellblocc600 ***@***.***>
Date: 16/10/23 8:05 am (GMT+10:00)
To: RogueMaster/flipperzero-firmware-wPlugins ***@***.***>
Cc: LeeroysHub ***@***.***>, Author ***@***.***>
Subject: Re: [RogueMaster/flipperzero-firmware-wPlugins] StatusBar drawn on menus (Issue #772)


Quick question does the newest update has android BLE spam

**Comment by AC9DJ** [comment]
There is a new BLE app on the Xtreme firmware that includes Android and Windows.
Talking Sasquatch covered it in. a video earlier today.
https://youtu.be/d8cSKNmBwX4?si=tSC2e72S7x2n073F

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by LeeroysHub** [comment]
Yes, you are right! Sorry about that. Its psrt of XFW, but Im sure RogueMaster will add it to RM very soon!


-------- Original message --------
From: AC9DJ ***@***.***>
Date: 16/10/23 11:10 am (GMT+10:00)
To: RogueMaster/flipperzero-firmware-wPlugins ***@***.***>
Cc: LeeroysHub ***@***.***>, Author ***@***.***>
Subject: Re: [RogueMaster/flipperzero-firmware-wPlugins] StatusBar drawn on menus (Issue #772)


There is a new BLE app on the Xtreme firmware that includes Android and Windows.
Talking Sasquatch covered it in. a video earlier today.
https://youtu.be/d8cSKNmBwX4?si=tSC2e72S7x2n073F

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by RogueMaster** [comment]
New BLE Spam app is in the latest RM build and coming to Public Release tonight!
