### ISSUE TITLE
Can't unlock game mode.

### ISSUE THREAD

**Issue by Selbyl** [RogueMaster/flipperzero-firmware-wPlugins#96]
Currently messing around with the current RougeMaster and it seems to be locked in game mode. I've tried different button combinations, but I have not figured out how to unlock it yet.

**Comment by RogueMaster** [comment]
Read me has unlock combo

**Comment by BotModeB** [comment]
hello, I can't get out of the game mode when I poke to the left in the "clock" section, I scroll to the left

**Comment by BotModeB** [comment]
It's not necessary anymore, I misread what to do

**Comment by Towaaaaaaa** [comment]
I can't unlock game mode

**Comment by Towaaaaaaa** [comment]
the combination of buttons does not work

**Comment by RogueMaster** [comment]
oh it does, if you got into clock just do it

**Comment by Towaaaaaaa** [comment]
everything worked out thanks!!!
