### ISSUE TITLE
Debug: Launch app on Flipper broken in VSCode

### ISSUE THREAD

**Issue by jamisonderek** [RogueMaster/flipperzero-firmware-wPlugins#982]
### Describe the bug.

In VSCode, when I choose "[Debug] Launch app on Flipper", the application fails to launch.  The firmware has it named "Apps" not "Applications" for a long time, but really the code is already invoking the CLI so all you need is the app path.

Proposed fix -- scripts\runfap.py - line 66
from:
                startup_command = f'"Applications" {fap_host_app}'
to:
                startup_command = f"{fap_host_app}"

### Reproduction

fbt vscode_dist
open VS Code
navigate to something you want to run.
Ctrl+Shift+B
Choose "[Debug] Launch app on Flipper"

### Target

vscode

**Comment by RogueMaster** [comment]
I don't use vscode but if you try that change, does it fix it?

**Comment by jamisonderek** [comment]
Yeah, it's been working great all day for me.  I'm doing some other work, so it's not as easy to fork + submit fix.

**Comment by RogueMaster** [comment]
No worries, thanks for your help!
