### ISSUE TITLE
Pokemon app keeps crashing my Flipper

### ISSUE THREAD

**Issue by LuxStatera** [RogueMaster/flipperzero-firmware-wPlugins#989]
### Describe the bug.

Each time I try to open the Pokemon app, it crashes my Flipper. Reboots everytime

### Reproduction

1. select apps
2. select gpio
3. select pokemon trading app
4. FLIPPER CRASHES

**Comment by RogueMaster** [comment]
Doesn't crash for me, you may have grabbed the app from somewhere wrong or aren't on the latest version. There are no crash issues with the app in its current revision.
