### ISSUE TITLE
issue NFC -> extra actions -> Unlock SLIX-L

### ISSUE THREAD

**Issue by heckpiet** [RogueMaster/flipperzero-firmware-wPlugins#992]
### Describe the bug.

can't use the app to write the file on the SD card.

![photo_2023-10-30_20-56-33](https://github.com/RogueMaster/flipperzero-firmware-wPlugins/assets/6371541/f817f3c3-29ff-4c97-aadc-6087ebca980b)

https://github.com/RogueMaster/flipperzero-firmware-wPlugins/assets/6371541/c2e4110f-c0b3-4302-90c5-38472412e53c

### Reproduction

1. switch on
2. navigate to NFC
3. extra actions
4. Unlock SLIX-L
5. place it on a Tonie
6. error message "Can not save key file"

**Comment by RogueMaster** [comment]
NFC Refactor will come, if it works there, it will work...

**Comment by heckpiet** [comment]
still a issue in Version
RM1031-1757-0.93.1-ef656e6

**Comment by RogueMaster** [comment]
> still a issue in Version
> RM1031-1757-0.93.1-ef656e6

And that version says in it's readme that the NFC Refactor is deferred... if the issue is still present once the refactor gets pushed in then open a ticket with OFW since our NFC will be the same as theirs...

**Comment by heckpiet** [comment]
thanks for the update

**Comment by disintegr8te** [comment]
OFW has it fixed in actual Release

**Comment by RogueMaster** [comment]
It is also fixed in the RC release

**Comment by disintegr8te** [comment]
> It is also fixed in the RC release

Yes, Tested the RC , reading them Works fine there.
But the Unlock Function is gone under Special Operations. Unleashed mentions it in the Changelog as known Regression.

**Comment by RogueMaster** [comment]
Yes, this is why my main release remains on the old NFC until the new NFC is no longer a regression
