### ISSUE TITLE
User defined repeat of IR command (Roomba Use Case)

### ISSUE THREAD

**Issue by Angel0ffDeath** [RogueMaster/flipperzero-firmware-wPlugins#996]
### Describe the enhancement you're suggesting.

Hi all,
iRobot Roomba uses IR signals as virtual wall to tell Roomba not to cross the border where wall is placed.
The virtual wall constantly sends IR signal and when Roomba detects it, it goes back. Of course the price of the virtual wall is almost like to build real wall :( .... 
The signal of the virtual wall is very simple - protocol RC5, address 0x0, command 0x40. 
It is not good idea to go after the Roomba with the flipper and when necessary to send the signal...
Of course it is possible to save the signal for about 30 min and then use Flipper as virtual wall, but it will be more elegant if it is possible in IR app to explain to repeat the signal for some time or until back button is pressed.
Have build one virtual wall with arduino nano, IR sender and battery and works perfect, but some persons cannot do that, so probably the above is good to be implemented.
Btw, as far as I know some other home robots are using the same principle, so it will be good to have enhancement like that.

Thank you and regards.

**Comment by RogueMaster** [comment]
Try the XRemote app under Apps->Infrared
